---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  filter:
    label: 클라우드 공급자
    default: 모든 클라우드 공급자
    options:
    - name: Amazon Web Services에서 직접 지원합니다
      alias: Amazon Web Services에서 직접 지원합니다
      id: aws
    - name: Google 클라우드
      alias: Google 클라우드
      id: gcp
    - name: Microsoft Azure를 참조하십시오
      alias: Azure를 지원합니다
      id: azure
  rss_page: release-notes/whats-new.html
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Astra Control Service 문서
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - title: Astra Control REST API로 자동화
    url: "/automation.html"
  - section: learn
  - section: support
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: Astra Control Service에 대해 알아보십시오
      url: "/get-started/intro.html"
    - title: 빠른 시작
      url: "/get-started/quick-start.html"
    - title: FAQ 를 참조하십시오
      url: "/get-started/faq.html"
  - title: Astra Control Service를 사용합니다
    links:
    - title: 애플리케이션 관리
      url: "/use/manage-apps.html"
    - title: 앱을 보호하십시오
      url: "/use/protect-apps.html"
    - title: 앱 마이그레이션
      url: "/use/clone-apps.html"
    - title: 대금 청구를 설정합니다
      url: "/use/set-up-billing.html"
  - title: Astra Control REST API 사용
    links:
    - title: 시작하십시오
      url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
    - title: API 참조입니다
      url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
    - title: API 워크플로우
      url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
  - title: 데모 자습서
    links:
    - title: Astra Control Service 비디오
      url: "/get-started/videos.html"
  - title: Astra 제어 센터
    links:
    - title: Astra Control Center 소개
      url: https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html
    - title: 새로운 소식
      url: https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html
    - title: 빠른 시작
      url: https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html
  - title: 솔루션 개요
    links:
    - title: Astra Control이 포함된 DataSlax Enterprise Apache Cassandra
      url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
    - title: Astra Control을 사용한 PostgreSQL DBaaS
      url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
    - title: Astra Control이 포함된 MySQL DBaaS
      url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
    - title: Jenkins 라이프사이클 관리 단순화
      url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
  - title: 블로그 커뮤니티
    links:
    - title: 아스트라 불화 채널
      url: https://discord.gg/NetApp
    - title: Astra Control 블로그
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Astra Control – 하이브리드 클라우드를 위한 애플리케이션 데이터 관리를 간소화합니다
      url: https://cloud.netapp.com/blog/blg-astra-control-simplifying-kubernetes-application-data-management-for-the-hybrid-cloud
    - title: Cloud Central의 Kubernetes Hub
      url: https://cloud.netapp.com/kubernetes-hub
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: 모든 Astra 문서
