---
sidebar: sidebar 
permalink: learn/choose-class-and-size.html 
keywords: service level, cvs, cvs-performance, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance 
summary: Astra Control Service는 Cloud Volumes Service for Google Cloud를 영구 볼륨의 스토리지 백엔드로 사용합니다. 서비스 수준, 스토리지 클래스 및 영구 볼륨 크기를 선택하면 성능 목표를 달성하는 데 어떤 도움이 되는지 알아야 합니다. 
---
= 서비스 유형, 스토리지 클래스 및 GKE 클러스터의 PV 크기입니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control Service는 영구 볼륨의 스토리지 백엔드 옵션으로 Cloud Volumes Service for Google Cloud, Google Persistent Disk 또는 NetApp Cloud Volumes ONTAP를 지원합니다.



== Google Cloud용 Cloud Volumes Service

Astra Control Service는 Cloud Volumes Service for Google Cloud를 영구 볼륨의 스토리지 백엔드로 사용할 수 있습니다. 서비스 유형, 스토리지 클래스 및 영구 볼륨 크기를 선택하면 성능 목표를 달성하는 데 어떤 도움이 되는지 알아야 합니다.



=== 개요

Google Cloud용 Cloud Volumes Service는 두 가지 서비스 유형, 즉 _CVS_와 _CVS - 성능 _ 을(를) 제공합니다. 이러한 서비스 유형은 특정 Google Cloud 지역에서 지원됩니다. https://["NetApp Cloud Central의 글로벌 지역 맵 으로 이동합니다"^] 클러스터가 상주하는 Google Cloud 영역에서 지원되는 서비스 유형을 식별합니다.

Kubernetes 클러스터가 특정 지역에 있어야 하는 경우 해당 지역에서 지원되는 서비스 유형을 사용하게 됩니다.

그러나 Google Cloud 지역 중에서 선택할 수 있는 유연성이 있다면 성능 요구 사항에 따라 다음 사항을 권장합니다.

* 중간~고성능 스토리지가 필요한 K8s 애플리케이션의 경우 CVS 성능을 지원하는 Google Cloud 영역을 선택하고 프리미엄 또는 익스트림 스토리지 클래스를 사용합니다. 이러한 워크로드에는 AI/ML 파이프라인, CI/CD 파이프라인, 미디어 처리, 관계형, NoSQL, 시계열 등을 포함한 데이터베이스 등이 있습니다
* 중간 규모의 스토리지 성능 요구(웹 애플리케이션, 범용 파일 스토리지 등)가 필요한 K8s 애플리케이션의 경우 표준 스토리지 클래스를 사용하여 CVS 또는 CVS 성능을 지원하는 Google Cloud 영역을 선택하십시오.


다음 표에서는 이 페이지에 설명된 정보를 빠르게 비교합니다.

[cols="5*"]
|===
| 서비스 유형입니다 | 사용 사례 | 지원 지역 | 스토리지 클래스 | 최소 볼륨 크기 


| CVS - 성능 | 중간 이상의 스토리지 성능 요구사항이 있는 애플리케이션 | https://["지원되는 Google Cloud 지역을 봅니다"^]  a| 
* NetApp-cvs-perf-standard
* NetApp-cvs-perf-프리미엄
* NetApp-cvs-perf-extreme

| 100GiB 


| CV | 중간 규모의 스토리지 성능 요구사항을 가진 애플리케이션 | https://["지원되는 Google Cloud 지역을 봅니다"^] | NetApp-CV-표준 | 300GiB 
|===


=== CVS - 성능 서비스 유형입니다

스토리지 클래스를 선택하고 영구 볼륨을 생성하기 전에 CVS - 성능 서비스 유형에 대해 자세히 알아보십시오.



==== 스토리지 클래스

CVS 성능 서비스 유형에는 Standard, Premium, Extreme의 세 가지 서비스 레벨이 지원됩니다. Astra Control Service에 클러스터를 추가하면 영구 볼륨의 기본 스토리지 클래스로 Standard, Premium 또는 Extreme을 선택하라는 메시지가 표시됩니다. 이러한 각 서비스 수준은 용량 및 대역폭 요구 사항에 따라 다르게 설계되었습니다.

스토리지 클래스의 이름은 _NetApp-cvs-perf-standard_,_NetApp-cvs-perf-premium_ 및 _NetApp-cvs-perf-extreme_입니다.

https://["Cloud Volumes Service for Google Cloud 문서에서 이러한 서비스 수준에 대해 자세히 알아보십시오"^].



==== 영구 볼륨 크기 및 성능

https://["Google Cloud 문서가 설명하는 대로"^]각 서비스 수준에 허용되는 대역폭은 프로비저닝된 용량 GiB 단위로 표시됩니다. 즉, 볼륨이 클수록 성능이 향상됩니다.

위에 링크된 Google Cloud 페이지를 읽어보시기 바랍니다. 또한 비용 비교와 예제를 통해 서비스 수준을 볼륨 크기와 연계하여 성능 목표를 달성하는 방법을 보다 잘 이해할 수 있습니다.



==== 최소 볼륨 크기입니다

Astra Control Service는 PVC가 더 작은 볼륨 크기를 요청하더라도 CVS-Performance 서비스 유형의 최소 볼륨 크기 100GiB를 사용하여 영구 볼륨을 프로비저닝합니다. 예를 들어, Hrom 차트의 PVC가 6GiB를 요청하는 경우 Astra Control Service는 자동으로 100GiB 볼륨을 프로비저닝합니다.



=== CVS 서비스 유형입니다

스토리지 클래스를 선택하고 영구 볼륨을 생성하기 전에 CVS 서비스 유형에 대해 자세히 알아보십시오.



==== 스토리지 클래스

CVS 서비스 유형인 Standard에서는 하나의 서비스 수준이 지원됩니다. CVS 서비스 유형이 지원되는 지역에서 클러스터를 관리하는 경우 Astra Control Service는 표준 서비스 수준을 영구 볼륨의 기본 스토리지 클래스로 사용합니다. 스토리지 클래스 이름은 _NetApp-CV-standard_입니다.

https://["Cloud Volumes Service for Google Cloud 문서에서 표준 서비스 수준에 대해 자세히 알아보십시오"^].



==== 영구 볼륨 크기 및 성능

CVS 서비스 유형에 허용되는 대역폭은 프로비저닝된 용량 GiB입니다. 즉, 볼륨이 클수록 성능이 향상됩니다.



==== 최소 볼륨 크기입니다

Astra Control Service는 PVC가 더 작은 볼륨 크기를 요청하더라도 CVS 서비스 유형의 최소 볼륨 크기 300GiB를 사용하여 영구 볼륨을 프로비저닝합니다. 예를 들어 20GiB가 요청되면 Astra Control Service는 300GiB 볼륨을 자동으로 프로비저닝합니다.

제한 사항으로 인해 PVC가 700-999 GiB의 볼륨을 요청하는 경우 Astra Control Service는 자동으로 1000GiB의 볼륨 크기를 프로비저닝합니다.



== Google 영구 디스크

Astra Control Service는 CSI(Container Storage Interface) 드라이버를 사용하여 Google 영구 디스크와 스토리지 백엔드로 인터페이스할 수 있습니다. 이 서비스는 Google에서 관리하는 블록 레벨 스토리지를 제공합니다.

https://["Google 영구 디스크에 대해 자세히 알아보십시오"^].

https://["Google 영구 디스크의 다양한 성능 수준에 대해 자세히 알아보십시오"^].



== NetApp Cloud Volumes ONTAP를 참조하십시오

성능 권장사항을 비롯한 NetApp Cloud Volumes ONTAP 구성에 대한 자세한 내용은 를 참조하십시오 https://["NetApp Cloud Volumes ONTAP 문서"^].
