---
sidebar: sidebar 
permalink: solutions/jenkins-deploy-from-helm-chart.html 
keywords: helm, jenkins, deploy apps, deploy jenkins, bitnami, helm chart, astra, astra control, kubernetes 
summary: Bitnami Helm 차트에서 Jenkins를 배포하는 방법을 알아보십시오. 클러스터에 Jenkins를 배포한 후 Astra Control에 애플리케이션을 등록할 수 있습니다. 
---
= 제어 차트에서 Jenkins를 배포합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/solutions/


에서 Jenkins를 배포하는 방법을 알아보십시오 https://bitnami.com/stack/jenkins/helm["Bitnami Helm 차트"^]. 클러스터에 Jenkins를 배포한 후 Astra Control에 애플리케이션을 등록할 수 있습니다.

Jenkins는 Astra Control의 검증된 애플리케이션입니다.

* https://docs.netapp.com/us-en/astra/learn/validated-vs-standard.html["Astra Control Service에서 검증된 앱과 표준 앱의 차이점을 알아보십시오"^].
* https://docs.netapp.com/us-en/astra-control-center/concepts/validated-vs-standard.html["Astra Control Center에서 검증된 앱과 표준 앱의 차이점을 알아보십시오"^].


이 지침은 Astra Control Service 및 Astra Control Center에 모두 적용됩니다.


NOTE: Google Marketplace에서 배포된 애플리케이션은 검증되지 않았습니다. 일부 사용자는 Postgres, MariaDB 및 MySQL의 Google Marketplace 배포에서 검색 및/또는 백업과 관련된 문제를 보고합니다.



== 요구 사항

* Astra Control에 추가된 클러스터.
+

NOTE: Astra Control Center의 경우 먼저 클러스터를 Astra Control Center에 추가하거나 앱을 먼저 추가할 수 있습니다.

* 클러스터에 적합한 kubecon무화과 함께 로컬 시스템에 설치된 Helm(버전 3.2+) 및 Kubectl의 업데이트 버전


Astra Control은 현재 를 지원하지 않습니다 https://plugins.jenkins.io/kubernetes/["Jenkins용 Kubernetes 플러그인"^]. 플러그인 없이 Kubernetes 클러스터에서 Jenkins를 실행할 수 있습니다. 플러그인은 Jenkins 클러스터에 확장성을 제공합니다.



== Jenkins를 설치합니다

이 프로세스에 대한 두 가지 중요한 참고 사항:

* 클러스터를 Astra Control Service에 추가한 후에 앱을 배포해야 합니다. Astra Control Center는 클러스터를 Astra Control Center에 추가하기 전이나 후에 애플리케이션을 수락합니다.
* 매개 변수는 기본적으로 설정되어 있는 것이 아닙니다.


.단계
. Bitnami 차트 repo 추가:
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. Jenkins 네임스페이스를 만들고 다음 명령을 사용하여 Jenkins를 배포합니다.
+
[listing]
----

helm install <name> bitnami/jenkins –-namespace <namespace> --create-namespace
–-set global.storageClass=<storage_class_name>
----
+

NOTE: 볼륨 크기가 변경되면 KI(Kibibyte), Mi(Mebibyte) 또는 Gi(gibibibyte) 단위를 사용합니다.

+
다음과 같은 경우에만 스토리지 클래스를 정의해야 합니다.

+
** Astra Control Service를 사용 중이며 기본 스토리지 클래스를 사용하고 싶지 않습니다.
** Astra Control Center를 사용 중이며 아직 클러스터를 Astra Control Center로 가져오지 않았습니다. 또는 클러스터를 가져왔지만 기본 스토리지 클래스를 사용하지 않으려는 경우




이렇게 하면 다음과 같은 작업을 수행할 수 있습니다.

* 네임스페이스를 만듭니다.
* 올바른 스토리지 클래스를 설정합니다.


Pod가 온라인 상태가 되면 Astra Control을 사용하여 앱을 관리할 수 있습니다. Astra Control을 사용하면 네임스페이스 수준이나 Helm 레이블을 사용하여 앱을 관리할 수 있습니다.
