---
sidebar: sidebar 
permalink: use/back-up-full-cluster.html 
keywords: backup, back up, backup apps, back up apps, take a backup, schedule backups, full, full backup, cluster backup, cluster, namespace, label, labels, namespaces 
summary: 클러스터의 모든 네임스페이스가 보호되도록 전체 클러스터 백업을 예약하여 앱을 보호합니다. 
---
= [기술 미리 보기] 전체 클러스터를 보호합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
클러스터에서 관리되지 않는 네임스페이스의 예약 및 자동 백업을 생성할 수 있습니다. 이러한 워크플로우는 NetApp에서 Kubernetes 서비스 계정, 역할 바인딩 및 cron 작업으로 제공되며 Python 스크립트로 조정됩니다.



== 작동 방식

전체 클러스터 백업 워크플로우를 구성하고 설치하면 cron 작업이 주기적으로 실행되고 아직 관리되지 않은 모든 네임스페이스를 보호하므로 설치 중에 선택한 일정에 따라 보호 정책이 자동으로 생성됩니다.

전체 클러스터 백업 워크플로우로 클러스터의 모든 관리되지 않는 네임스페이스를 보호하지 않으려면 레이블 기반 백업 워크플로우를 활용할 수 있습니다. 레이블 기반 백업 워크플로는 또한 cron 작업을 사용하지만 관리되지 않는 모든 네임스페이스를 보호하는 대신 브론즈, 실버 또는 골드 백업 정책을 기반으로 선택적으로 네임스페이스를 보호하기 위해 제공하는 레이블을 통해 네임스페이스를 식별합니다.

선택한 워크플로의 범위에 속하는 새 네임스페이스가 만들어지면 관리자 작업 없이 자동으로 보호됩니다. 이러한 워크플로는 클러스터 단위로 구현되므로 클러스터의 중요도에 따라 각 클러스터에서 고유한 보호 수준을 가진 워크플로우를 사용할 수 있습니다.

.예: 전체 클러스터 보호
예를 들어, 전체 클러스터 백업 워크플로우를 구성하고 설치하면 네임스페이스의 모든 앱이 관리자의 추가 작업 없이 주기적으로 관리 및 보호됩니다. 워크플로를 설치할 때 네임스페이스가 존재할 필요가 없습니다. 나중에 네임스페이스가 추가되면 네임스페이스가 보호됩니다.

.예: 레이블 기반 보호
더 세분화하려면 레이블 기반 워크플로를 사용할 수 있습니다. 예를 들어 이 워크플로를 설치하고 필요한 보호 수준에 따라 보호할 네임스페이스에 여러 레이블 중 하나를 적용하도록 사용자에게 지시할 수 있습니다. 따라서 사용자는 이러한 레이블 중 하나로 네임스페이스를 만들 수 있으며 관리자에게 알릴 필요가 없습니다. 새로운 네임스페이스와 IT 내의 모든 앱이 자동으로 보호됩니다.



== 모든 네임스페이스의 예약된 백업을 생성합니다

전체 클러스터 백업 워크플로우를 사용하여 클러스터의 모든 네임스페이스에 대해 예약된 백업을 생성할 수 있습니다.

.단계
. 클러스터에 대한 네트워크 액세스 권한이 있는 시스템에 다음 파일을 다운로드합니다.
+
** https://raw.githubusercontent.com/NetApp/netapp-astra-toolkits/main/examples/fullcluster-backup/components.yaml["components.yaml CRD 파일"]
** https://raw.githubusercontent.com/NetApp/netapp-astra-toolkits/main/examples/fullcluster-backup/protectCluster.py["protectCluster.py Python 스크립트"]


. 툴킷을 구성하고 설치하려면 https://github.com/NetApp/netapp-astra-toolkits/blob/main/examples/fullcluster-backup/README.md["포함된 지침을 따릅니다"^].




== 특정 네임스페이스의 예약된 백업을 생성합니다

레이블 기반 백업 워크플로우를 사용하여 레이블을 기준으로 특정 네임스페이스의 예약된 백업을 만들 수 있습니다.

.단계
. 클러스터에 대한 네트워크 액세스 권한이 있는 시스템에 다음 파일을 다운로드합니다.
+
** https://raw.githubusercontent.com/NetApp/netapp-astra-toolkits/main/examples/labelbased-backup/components.yaml["components.yaml CRD 파일"]
** https://raw.githubusercontent.com/NetApp/netapp-astra-toolkits/main/examples/labelbased-backup/protectCluster.py["protectCluster.py Python 스크립트"]


. 툴킷을 구성하고 설치하려면 https://github.com/NetApp/netapp-astra-toolkits/blob/main/examples/labelbased-backup/README.md["포함된 지침을 따릅니다"^].

