---
sidebar: sidebar 
permalink: use/manage-roles.html 
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint, constraints 
summary: 역할에 제약 조건을 추가하여 사용자 역할을 관리하는 방법에 대해 알아봅니다. 
---
= 역할을 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


네임스페이스 제약 조건을 추가하고 이러한 제약 조건에 대한 사용자 역할을 제한하여 역할을 관리할 수 있습니다. 이렇게 하면 조직 내의 리소스에 대한 액세스를 제어할 수 있습니다. Astra Control UI 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 역할을 관리합니다.



== 역할에 네임스페이스 제약 조건을 추가합니다

관리자 또는 소유자 사용자는 네임스페이스 제약 조건을 추가할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. Actions * 열에서 Member 또는 Viewer 역할을 가진 사용자의 메뉴 버튼을 선택합니다.
. 역할 편집 * 을 선택합니다.
. 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
이 확인란은 구성원 또는 뷰어 역할에만 사용할 수 있습니다. 역할 * 드롭다운 목록에서 다른 역할을 선택할 수 있습니다.

. 구속 조건 추가 * 를 선택합니다.
+
네임스페이스 또는 네임스페이스 레이블별로 사용 가능한 제약 조건 목록을 볼 수 있습니다.

. 네임스페이스 구성 방법에 따라 * 제약 조건 유형 * 드롭다운 목록에서 * Kubernetes 네임스페이스 * 또는 * Kubernetes 네임스페이스 레이블 * 을 선택합니다.
. 목록에서 하나 이상의 네임스페이스 또는 레이블을 선택하여 해당 네임스페이스로 역할을 제한하는 제약 조건을 구성합니다.
. Confirm * 을 선택합니다.
+
역할 편집 * 페이지에는 이 역할에 대해 선택한 제약 조건 목록이 표시됩니다.

. Confirm * 을 선택합니다.
+
계정 * 페이지의 * 역할 * 열에서 구성원 또는 뷰어 역할에 대한 제약 조건을 볼 수 있습니다.




NOTE: 역할에 대한 제약 조건을 설정하고 제약 조건을 추가하지 않고 * 확인 * 을 선택하면 역할이 전체 제한 사항으로 간주됩니다(역할에 네임스페이스가 할당된 리소스에 대한 액세스가 거부됨).



== 역할에서 네임스페이스 제약 조건을 제거합니다

관리자 또는 소유자 사용자는 역할에서 네임스페이스 제약 조건을 제거할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. Actions * 열에서 활성 제약 조건이 있는 Member 또는 Viewer 역할을 가진 사용자의 메뉴 버튼을 선택합니다.
. 역할 편집 * 을 선택합니다.
+
역할 편집 * 대화 상자에 해당 역할에 대한 활성 제약 조건이 표시됩니다.

. 제거할 구속 조건의 오른쪽에 있는 * X * 를 선택합니다.
. Confirm * 을 선택합니다.




== 를 참조하십시오

* link:../learn/user-roles-namespaces.html["사용자 역할 및 네임스페이스"]

