---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: 추가 버킷을 추가하고 클라우드 공급자의 클러스터에 대한 기본 버킷을 변경하여 Astra가 백업 및 클론에 사용하는 버킷을 관리합니다. 
---
= 버킷을 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra가 백업 및 클론에 사용하는 버킷을 관리할 수 있습니다. 클라우드 인스턴스에서 추가 버킷을 추가하고, 기존 버킷을 제거하고, Kubernetes 클러스터의 기본 버킷을 변경할 수 있습니다.

소유자 및 관리자만 버킷을 관리할 수 있습니다.



== Astra Control이 버킷을 사용하는 방식

클라우드 인스턴스를 위한 첫 번째 Kubernetes 클러스터 관리를 시작할 때 Astra Control Service는 이를 위한 초기 버킷을 생성합니다 link:manage-cloud-instances.html["클라우드 인스턴스"^].

수동으로 버킷을 클라우드 인스턴스의 기본 버킷으로 지정할 수 있습니다. 이 경우 Astra Control Service는 해당 클라우드 인스턴스의 관리되는 클러스터에서 생성한 백업 및 클론에 대해 기본적으로 이 버킷을 사용합니다(백업에 다른 버킷을 선택할 수 있음). 클라우드 인스턴스의 관리되는 클러스터에서 다른 클러스터로 애플리케이션의 라이브 클론을 수행하는 경우 Astra Control Service는 소스 클라우드 인스턴스에 대한 기본 버킷을 사용하여 클론 작업을 수행합니다.

여러 클라우드 인스턴스의 기본 버킷과 동일한 버킷을 설정할 수 있습니다.

보호 정책을 생성하거나 임시 백업을 시작할 때 모든 버킷에서 선택할 수 있습니다.


TIP: Astra Control Service는 백업 또는 클론을 시작하기 전에 대상 버킷에 액세스할 수 있는지 여부를 확인합니다.



== 기존 버킷을 봅니다

Astra Control Service에서 사용할 수 있는 버킷 목록을 보고 해당 상태를 확인하고 클라우드 인스턴스의 기본 버킷(정의된 경우)을 식별합니다.

버킷은 다음 상태 중 하나를 가질 수 있습니다.

보류 중:: 버킷을 추가하면 보류 중인 상태에서 시작되고 Astra Control이 이를 검색합니다.
사용 가능:: 이 버킷은 Astra Control에서 사용할 수 있습니다.
제거되었습니다:: 현재는 버킷이 작동하지 않습니다. 상태 아이콘 위에 마우스를 올려 놓으면 문제가 무엇인지 확인할 수 있습니다.
+
--
버킷이 제거된 상태인 경우에도 기본 버킷으로 설정하고 보호 일정에 할당할 수 있습니다. 하지만 데이터 보호 작업이 시작될 때 버킷이 가용 상태가 아니면 해당 작업이 실패합니다.

--


.단계
. 버킷 * 으로 이동합니다.
+
Astra Control Service에서 사용할 수 있는 버킷 목록이 표시됩니다.





== 추가 버킷을 추가합니다

언제든지 추가 버킷을 추가할 수 있습니다. 따라서 보호 정책을 생성하거나 임시 백업을 시작할 때 버킷 중에서 선택할 수 있으며, 클라우드 인스턴스에서 사용하는 기본 버킷을 변경할 수 있습니다.

다음 유형의 버킷을 추가할 수 있습니다.

* Amazon Web Services에서 직접 지원합니다
* 일반 S3
* Google 클라우드 플랫폼
* Microsoft Azure를 참조하십시오
* NetApp ONTAP S3
* NetApp StorageGRID S3


.시작하기 전에
* 기존 버킷의 이름을 알고 있어야 합니다.
* Astra Control에 버킷 관리에 필요한 권한을 제공하는 버킷에 대한 자격 증명이 있어야 합니다.


ifdef::azure[]

* 버킷이 Microsoft Azure에 있는 경우:
+
** 버킷은 _Astra-backup-rg_이라는 리소스 그룹에 속해야 합니다.
** Azure 저장소 계정 인스턴스 성능 설정이 "프리미엄"으로 설정된 경우 "프리미엄 계정 유형" 설정을 "Blob 차단"으로 설정해야 합니다.




endif::azure[]

.단계
. 버킷 * 으로 이동합니다.
. 추가 * 를 선택하고 프롬프트에 따라 버킷을 추가합니다.
+
** * 유형 *: 클라우드 공급자를 선택하십시오.
** * 기존 버킷 이름 *: 버킷의 이름을 입력합니다.
** * 설명 *: 버킷에 대한 설명을 선택적으로 입력합니다.




ifdef::azure[]

* * 저장소 계정 * (Azure에만 해당): Azure 저장소 계정의 이름을 입력합니다. 이 버킷은 이름이 _Astra-backup-rg_인 리소스 그룹에 속해야 합니다.


endif::azure[]

ifdef::aws[]

* * S3 서버 이름 또는 IP 주소 * (AWS 및 S3 버킷 유형만 해당): 해당 지역에 해당하는 S3 엔드포인트의 정규화된 도메인 이름을 에 입력합니다 `https://`. 을 참조하십시오 https://docs.aws.amazon.com/general/latest/gr/s3.html["아마존 문서"^] 를 참조하십시오.


endif::aws[]

* * 자격 증명 선택 *: Astra Control Service에 버킷 관리에 필요한 권한을 제공하는 자격 증명을 입력합니다. 제공해야 하는 정보는 버킷 유형에 따라 다릅니다.
+
.. 버킷을 추가하려면 * 추가 * 를 선택합니다.




.결과
Astra Control Service가 버킷을 추가합니다. 이제 보호 정책을 생성하거나 임시 백업을 수행할 때 이 버킷을 선택할 수 있습니다. 이 버킷을 클라우드 인스턴스의 기본 버킷으로 설정할 수도 있습니다.



== 기본 버킷을 변경합니다

클라우드 인스턴스의 기본 버킷을 변경할 수 있습니다. Astra Control Service는 기본적으로 백업 및 클론에 이 버킷을 사용합니다. 각 클라우드 인스턴스에는 고유한 기본 버킷이 있습니다.


NOTE: Astra Control은 클라우드 인스턴스에 대해 기본 버킷을 자동으로 할당하지 않습니다. 두 클러스터 간에 애플리케이션 클론 작업을 수행하기 전에 클라우드 인스턴스의 기본 버킷을 수동으로 설정해야 합니다.

.단계
. 클라우드 인스턴스 * 로 이동합니다.
. 편집할 클라우드 인스턴스의 * 작업 * 열에서 구성 메뉴를 선택합니다.
. 편집 * 을 선택합니다.
. 버킷 목록에서 이 클라우드 인스턴스의 기본 버킷을 만들 버킷을 선택합니다.
. Update * 를 선택합니다.




== 버킷을 탈거하십시오

더 이상 사용하지 않거나 상태가 불량한 버킷을 제거할 수 있습니다. 오브젝트 저장소 구성을 단순하고 최신 상태로 유지하기 위해 이 작업을 수행할 수 있습니다.

[NOTE]
====
* 기본 버킷을 제거할 수 없습니다. 해당 버킷을 제거하려면 먼저 다른 버킷을 기본값으로 선택하십시오.
* 버킷의 클라우드 공급자 보존 기간이 만료되기 전에는 WORM(Write Once Read Many) 버킷을 제거할 수 없습니다. 웜 버킷은 버킷 이름 옆에 "잠김"으로 표시됩니다.


====
.시작하기 전에
* 시작하기 전에 이 버킷에 대해 실행 중이거나 완료된 백업이 없는지 확인해야 합니다.
* 예약된 백업에 버킷이 사용되지 않는지 확인해야 합니다.


있는 경우 계속할 수 없습니다.

.단계
. 버킷 * 으로 이동합니다.
. Actions * 메뉴에서 * Remove * 를 선택합니다.
+

NOTE: Astra Control은 먼저 버킷에 백업을 사용하는 스케줄 정책이 없고 제거할 버킷에 활성 백업이 없음을 보장합니다.

. 작업을 확인하려면 "remove"를 입력합니다.
. 예, 버킷 제거 * 를 선택합니다.




== [기술 미리보기] 사용자 지정 리소스를 사용하여 버킷을 관리합니다

애플리케이션 클러스터에서 Astra Control CR(사용자 지정 리소스)을 사용하여 버킷을 추가할 수 있습니다. 애플리케이션과 영구 스토리지를 백업하려는 경우나 클러스터 간에 애플리케이션을 클론 복제하려는 경우에는 오브젝트 저장소 버킷 공급자를 추가하는 것이 중요합니다. Astra Control은 이러한 백업 또는 클론을 정의한 오브젝트 저장소 버킷에 저장합니다. 사용자 지정 리소스 방법을 사용하는 경우 애플리케이션 스냅샷 기능을 사용하려면 버킷이 필요합니다.

애플리케이션 구성과 영구 스토리지를 동일한 클러스터에 클론 복제하려는 경우 Astra Control에 버킷이 필요하지 않습니다.

Astra Control의 버킷 맞춤형 리소스를 AppVault라고 합니다. 이 CR에는 보호 작업에 사용되는 버킷에 필요한 구성이 포함되어 있습니다.

.시작하기 전에
* Astra Control Center에서 관리하는 클러스터에서 연결할 수 있는 버킷이 있어야 합니다.
* 버킷에 대한 자격 증명이 있는지 확인하십시오.
* 버킷이 다음 유형 중 하나인지 확인합니다.
+
** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure를 참조하십시오
** 일반 S3





NOTE: AWS(Amazon Web Services) 및 GCP(Google Cloud Platform)는 일반 S3 버킷 유형을 사용합니다.


NOTE: Astra Control Center는 Amazon S3를 일반 S3 버킷 공급자로 지원하지만, Astra Control Center는 Amazon의 S3 지원을 주장하는 모든 오브젝트 저장소 공급업체를 지원하지 않을 수 있습니다.

.단계
. 사용자 정의 리소스(CR) 파일을 만들고 이름을 지정합니다(예: `astra-appvault.yaml`)를 클릭합니다.
. 다음 특성을 구성합니다.
+
** *metadata.name*: _ (필수) _ AppVault 사용자 정의 리소스의 이름입니다.
** * spec.prefix *: _ (선택 사항) _ AppVault에 저장된 모든 요소의 이름 앞에 붙는 경로입니다.
** *spec.providerConfig*: _ (필수) _ 지정된 공급자를 사용하여 AppVault에 액세스하는 데 필요한 구성을 저장합니다.
** *spec.providerCredentials*: _ (필수) _ 지정된 공급자를 사용하여 AppVault에 액세스하는 데 필요한 자격 증명에 대한 참조를 저장합니다.
+
*** *spec.providerCredentials.valueFromSecret*: _ (선택 사항) _ 자격 증명 값이 비밀에서 와야 함을 나타냅니다.
+
**** * KEY *: _ (valueFromSecret을 사용하는 경우 필수) _ 선택할 암호의 유효한 키입니다.
**** * name *: _ (valueFromSecret을 사용하는 경우 필수) _ 이 필드의 값을 포함하는 암호의 이름입니다. 같은 네임스페이스에 있어야 합니다.




** *spec.providerType*: _ (필수) _ 백업을 제공하는 항목을 결정합니다(예: NetApp ONTAP S3 또는 Microsoft Azure).
+
YAML 예:

+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra-appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----


. 를 채운 후 `astra-appvault.yaml` 올바른 값이 있는 파일에 CR을 적용합니다.
+
[source, console]
----
kubectl apply -f astra-appvault.yaml -n astra-connector
----
+

NOTE: 버킷을 추가하면 Astra Control이 기본 버킷 표시기로 하나의 버킷을 표시합니다. 사용자가 만든 첫 번째 버킷이 기본 버킷이 됩니다. 양동이 추가될 때 나중에 결정할 수 있습니다 link:../use/manage-buckets.html#set-the-default-bucket["다른 기본 버킷을 설정합니다"^].





== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 사용합니다"^]

