---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: 추가 버킷을 추가하고 클라우드 공급자의 클러스터에 대한 기본 버킷을 변경하여 Astra가 백업 및 클론에 사용하는 버킷을 관리합니다. 
---
= 버킷을 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
추가 버킷을 추가하고 클라우드 인스턴스의 Kubernetes 클러스터에 대한 기본 버킷을 변경하여 Astra가 백업 및 클론에 사용하는 버킷을 관리합니다.

관리자만 버킷을 추가하고 수정할 수 있습니다.



== Astra Control이 버킷을 사용하는 방식

첫 번째 Kubernetes 클러스터 관리를 시작할 때 Astra Control Service는 관리형 클러스터와 같은 지리적 위치에서의 클라우드 공급자 기본 버킷을 생성합니다.

Astra Control Service는 사용자가 생성한 백업 및 클론에 이 기본 버킷을 사용합니다. 그런 다음 백업을 사용하여 클러스터 간에 앱을 복원 및 클론 복제할 수 있습니다.

Astra Control Service에 추가 버킷을 추가하는 경우 보호 정책을 생성할 때 해당 버킷 중에서 선택할 수 있습니다. 또한 Astra Control Service가 임시 백업 및 클론에 사용하는 기본 버킷을 변경할 수 있습니다. 하나의 클라우드 공급자에서 다른 클라우드 공급자로 버킷을 클론 복제할 수 없습니다. 클라우드 공급자 간에 데이터를 마이그레이션하려면 연결된 애플리케이션을 클론 복제하십시오.


TIP: Astra Control Service는 백업 또는 클론을 시작하기 전에 대상 버킷에 액세스할 수 있는지 여부를 확인합니다.



== 기존 버킷을 봅니다

Astra Control Service에서 사용할 수 있는 버킷 목록을 보고 해당 상태를 확인하고 클라우드 공급자의 기본 버킷을 식별합니다.

버킷은 다음 상태 중 하나를 가질 수 있습니다.

보류 중:: 버킷을 추가한 후 보류 중인 상태에서 시작하여 Astra Control이 처음으로 이 버킷을 확인합니다.
사용 가능:: 이 버킷은 Astra Control에서 사용할 수 있습니다.
제거되었습니다:: 현재는 버킷이 작동하지 않습니다. 상태 아이콘 위에 마우스를 올려 놓으면 문제가 무엇인지 확인할 수 있습니다.
+
--
버킷이 제거된 상태인 경우에도 기본 버킷으로 설정하고 보호 일정에 할당할 수 있습니다. 하지만 데이터 보호 작업이 시작될 때 버킷이 가용 상태가 아니면 해당 작업이 실패합니다.

--


.단계
. 버킷 * 으로 이동합니다.
+
Astra Control Service에서 사용할 수 있는 버킷 목록이 표시됩니다.





== 추가 버킷을 추가합니다

클라우드 공급자에서 클러스터 관리를 시작한 후에는 언제든지 추가 버킷을 추가할 수 있습니다. 따라서 보호 정책을 생성할 때 버킷 중에서 선택하고 임시 백업 및 클론의 기본 버킷을 변경할 수 있습니다.

.필요한 것
* 클라우드 공급자에 있는 기존 버킷의 이름입니다.


ifdef::azure[]

* 버킷이 Azure에 있는 경우:
+
** 버킷은 _Astra-backup-rg_이라는 리소스 그룹에 속해야 합니다.
** Azure 저장소 계정 인스턴스 성능 설정이 "프리미엄"으로 설정된 경우 "프리미엄 계정 유형" 설정을 "Blob 차단"으로 설정해야 합니다.




endif::azure[]

.단계
. 버킷 * 으로 이동합니다.
. 추가 * 를 선택하고 프롬프트에 따라 버킷을 추가합니다.
+
** * 유형 *: 클라우드 공급자를 선택하십시오.
+
클라우드 공급자는 Astra Control Service가 해당 클라우드 공급자에서 실행 중인 클러스터를 관리하기 시작한 후에만 사용할 수 있습니다.

** * 기존 버킷 이름 *: 버킷의 이름을 입력합니다.
** * 설명 *: 버킷에 대한 설명을 선택적으로 입력합니다.




ifdef::azure[]

* * 저장소 계정 * (Azure에만 해당): Azure 저장소 계정의 이름을 입력합니다. 이 버킷은 이름이 _Astra-backup-rg_인 리소스 그룹에 속해야 합니다.


endif::azure[]

ifdef::aws[]

* * S3 서버 이름 또는 IP 주소 * (AWS만 해당): 해당 지역에 해당하는 S3 엔드포인트의 정규화된 도메인 이름을 입력하지 않고 입력합니다 `https://`. 을 참조하십시오 https://docs.aws.amazon.com/general/latest/gr/s3.html["아마존 문서"^] 를 참조하십시오.


endif::aws[]

* * 자격 증명 선택 *: Astra Control Service에 버킷 관리에 필요한 권한을 제공하는 자격 증명을 선택합니다.
+
.. 버킷을 추가하려면 * 추가 * 를 선택합니다.




.결과
Astra Control Service는 추가 버킷을 추가합니다. 이제 보호 정책을 생성할 때 버킷을 선택할 수 있습니다.



== 기본 버킷을 변경합니다

Astra Control Service가 백업 및 클론에 사용해야 하는 기본 버킷을 변경합니다. 각 클라우드 인스턴스에는 고유한 기본 버킷이 있습니다.

Astra Control Service는 기존 백업에서 클론을 생성하지 않도록 선택할 경우 임시 백업 및 임시 클론의 클라우드 인스턴스에 기본 버킷을 사용합니다.


NOTE: Astra Control은 클라우드 인스턴스에 대해 기본 버킷을 자동으로 할당하지 않습니다. 두 클러스터 간에 애플리케이션 클론 작업을 수행하기 전에 클라우드 인스턴스의 기본 버킷을 수동으로 설정해야 합니다.

.단계
. 클라우드 인스턴스 * 로 이동합니다.
. 편집할 클라우드 인스턴스의 * 작업 * 열에서 구성 메뉴를 선택합니다.
. 편집 * 을 선택합니다.
. 버킷 목록에서 이 클라우드 인스턴스의 기본 버킷을 만들 버킷을 선택합니다.
. Update * 를 선택합니다.




== 버킷을 탈거하십시오

더 이상 사용하지 않거나 상태가 불량한 버킷을 제거할 수 있습니다. 오브젝트 저장소 구성을 단순하고 최신 상태로 유지하기 위해 이 작업을 수행할 수 있습니다.

기본 버킷을 제거할 수 없습니다. 해당 버킷을 제거하려면 먼저 다른 버킷을 기본값으로 선택하십시오.

.필요한 것
* 시작하기 전에 이 버킷에 대해 실행 중이거나 완료된 백업이 없는지 확인해야 합니다.
* 예약된 백업에 버킷이 사용되지 않는지 확인해야 합니다.


있는 경우 계속할 수 없습니다.

.단계
. 버킷 * 으로 이동합니다.
. Actions * 메뉴에서 * Remove * 를 선택합니다.
+

NOTE: Astra Control은 먼저 버킷에 백업을 사용하는 스케줄 정책이 없고 제거할 버킷에 활성 백업이 없음을 보장합니다.

. 작업을 확인하려면 "remove"를 입력합니다.
. 예, 버킷 제거 * 를 선택합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 사용합니다"^]

