---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 언제든지 계정에서 클라우드 공급자 자격 증명을 추가 및 제거할 수 있습니다. Astra Control은 이러한 자격 증명을 사용하여 사용자를 대신하여 리소스를 제공합니다. 
---
= 자격 증명을 추가 및 제거합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


언제든지 계정에서 클라우드 공급자 자격 증명을 추가 및 제거할 수 있습니다. Astra Control은 이러한 자격 증명을 사용하여 Kubernetes 클러스터, 클러스터에 있는 앱을 검색하고 대신 리소스를 프로비저닝합니다.

Astra Control의 모든 사용자는 동일한 자격 증명 세트를 공유합니다.



== 자격 증명을 추가합니다

Astra Control에 자격 증명을 추가하는 가장 일반적인 방법은 클러스터를 관리하는 것이지만 계정 페이지에서 자격 증명을 추가할 수도 있습니다. 그러면 추가 Kubernetes 클러스터를 관리할 때 자격 증명을 선택할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* GKE의 경우 필요한 권한이 있는 서비스 계정에 대한 서비스 계정 키 파일이 있어야 합니다. link:../get-started/set-up-google-cloud.html["서비스 계정 설정 방법에 대해 알아보십시오"].
* AKS의 경우 서비스 보안 주체를 생성할 때 Azure CLI의 출력이 포함된 JSON 파일이 있어야 합니다. link:../get-started/set-up-microsoft-azure-with-anf.html["서비스 보안 주체를 설정하는 방법에 대해 알아봅니다"].
+
JSON 파일에 추가하지 않은 경우 Azure 구독 ID도 필요합니다.



.단계
. 계정 > 자격 증명 * 을 선택합니다.
. 자격 증명 추가 * 를 선택합니다.
. Microsoft Azure * 또는 * Google Cloud Platform * 을 선택합니다.
. Astra Control의 다른 자격 증명과 구별되는 자격 증명의 이름을 입력합니다.
. 필요한 자격 증명을 입력합니다.
+
.. * Microsoft Azure *: JSON 파일을 업로드하거나 클립보드에서 해당 JSON 파일의 내용을 붙여넣어 Azure 서비스 교장에게 자세한 정보를 Astra Control에 제공합니다.
+
JSON 파일에는 서비스 보안 주체를 생성할 때 Azure CLI의 출력이 포함되어야 합니다. 또한 구독 ID를 포함할 수 있으므로 Astra Control에 자동으로 추가됩니다. 그렇지 않으면 JSON을 제공한 후 ID를 수동으로 입력해야 합니다.

.. * Google Cloud Platform *: 파일을 업로드하거나 클립보드의 콘텐츠를 붙여넣어 Google Cloud 서비스 계정 키 파일을 제공합니다.


. 자격 증명 추가 * 를 선택합니다.


이제 Astra Control에 클러스터를 추가할 때 자격 증명을 선택할 수 있습니다.



== 자격 증명을 제거합니다

언제든지 계정에서 자격 증명을 제거합니다. 자격 증명은 이후에 제거해야 합니다 link:unmanage.html["모든 클러스터 관리를 취소합니다"]자격 증명을 순환하지 않는 경우( 참조 <<Rotate credentials>>)를 클릭합니다.


NOTE: Astra Control에 추가하는 첫 번째 자격 증명 세트는 항상 사용 중입니다. Astra Control은 자격 증명을 사용하여 백업 버킷에 인증하기 때문입니다. 이러한 자격 증명을 제거하지 않는 것이 좋습니다.

.단계
. 계정 > 자격 증명 * 을 선택합니다.
. 제거할 자격 증명에 대한 * 상태 * 열의 드롭다운 목록을 선택합니다.
. 제거 * 를 선택합니다.
. 삭제할 자격 증명의 이름을 입력한 다음 * 예, 자격 증명 제거 * 를 선택합니다.


Astra Control은 계정에서 자격 증명을 제거합니다.



== 자격 증명 회전

계정에서 자격 증명을 회전할 수 있습니다. 자격 증명을 회전하는 경우 백업이 진행 중인 상태(예약 또는 필요 시)가 없을 때 유지 관리 창에서 자격 증명을 회전합니다.

.단계
. 의 단계에 따라 기존 자격 증명을 제거합니다 <<Remove credentials>>.
. 의 단계에 따라 새 자격 증명을 추가합니다 <<Add credentials>>.
. 새 자격 증명을 사용하도록 모든 버킷을 업데이트합니다.
+
.. 스토리지 관리 * 에서 * 버킷 * 을 선택합니다.
.. 편집할 버킷의 * Actions * 열에서 드롭다운 목록을 선택합니다.
.. 편집 * 을 선택합니다.
.. 자격 증명 선택 * 섹션에서 Astra Control에 추가한 새 자격 증명을 선택합니다.
.. Update * 를 선택합니다.
.. 시스템에 남아 있는 버킷에 대해 * b * ~ * e * 단계를 반복합니다.




Astra Control은 새로운 클라우드 공급자 자격 증명을 사용하기 시작합니다.
