---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: invite users, add users, remove users, delete users 
summary: Astra Control 계정에 가입하도록 사용자를 초대하고 더 이상 계정에 액세스할 수 없는 사용자를 제거합니다. 
---
= 사용자를 초대하고 제거합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control 계정에 가입하도록 사용자를 초대하고 더 이상 계정에 액세스할 수 없는 사용자를 제거합니다.



== 사용자를 초대합니다

계정 소유자와 관리자는 다른 사용자를 Astra Control 계정에 가입하도록 초대할 수 있습니다.

.단계
. 사용자에게 가 있는지 확인합니다 link:../get-started/register.html["Cloud Central 로그인"].
. 계정 * 을 선택합니다.
. 사용자 * 탭에서 * 초대 * 를 선택합니다.
. 사용자의 이름, 이메일 주소 및 역할을 입력합니다.
+
다음 사항에 유의하십시오.

+
** 이메일 주소는 사용자가 Cloud Central에 등록하는 데 사용한 이메일 주소와 일치해야 합니다.
** 각 역할은 다음과 같은 권한을 제공합니다.
+
*** 소유자 * 는 관리자 권한을 가지며 계정을 삭제할 수 있습니다.
*** Admin * 은 구성원 권한을 가지며 다른 사용자를 초대할 수 있습니다.
*** 회원 * 은 앱과 클러스터를 완벽하게 관리할 수 있습니다.
*** Viewer * 는 리소스를 볼 수 있습니다.




. 멤버 또는 뷰어 역할이 있는 사용자에게 제약 조건을 추가하려면 * 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
제약 조건 추가에 대한 자세한 내용은 을 참조하십시오 link:manage-roles.html["역할을 관리합니다"].

. 다른 사용자를 초대하려면 * 다른 사용자 추가 * 를 선택하고 새 사용자에 대한 정보를 입력합니다.
+
한 번에 최대 10명의 사용자를 초대할 수 있습니다. 사용자 초대 * 대화 상자의 왼쪽에서 초대하는 사용자 사이를 탐색할 수 있습니다.

. 사용자 초대 * 를 선택합니다.


.결과
사용자 또는 사용자는 계정에 가입하도록 초대하는 이메일을 받게 됩니다.



== 사용자의 역할을 변경합니다

계정 소유자는 모든 사용자의 역할을 변경할 수 있고 계정 관리자는 관리자, 구성원 또는 뷰어 역할을 가진 사용자의 역할을 변경할 수 있습니다.

.단계
. 계정 * 을 선택합니다.
. 사용자 * 탭의 * 작업 * 열에서 해당 사용자의 메뉴를 선택합니다.
. 역할 편집 * 을 선택합니다.
. 새 역할을 선택합니다.
. 멤버 또는 뷰어 역할이 있는 사용자에게 제약 조건을 추가하려면 * 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
제약 조건 추가에 대한 자세한 내용은 을 참조하십시오 link:manage-roles.html["역할을 관리합니다"].

. Confirm * 을 선택합니다.


.결과
Astra Control은 선택한 새 역할에 따라 사용자의 권한을 업데이트합니다.



== 사용자를 제거합니다

소유자 역할을 가진 사용자는 언제든지 계정에서 다른 사용자를 제거할 수 있습니다.

.단계
. 계정 * 을 선택합니다.
. 사용자 * 탭에서 제거할 사용자를 선택합니다.
. Actions * 열에서 메뉴를 선택하고 * Remove user * 를 선택합니다.
. 메시지가 표시되면 "remove"를 입력하여 삭제를 확인한 다음 * 예, 사용자 제거 * 를 선택합니다.


.결과
Astra Control은 사용자를 계정에서 제거합니다.
