---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster 
summary: Astra Control에서 더 이상 관리하지 않으려는 응용 프로그램 또는 클러스터를 제거합니다. 
---
= 앱 및 클러스터 관리를 취소합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control에서 더 이상 관리하지 않으려는 응용 프로그램 또는 클러스터를 제거합니다.



== 앱 관리를 중지합니다

Astra Control에서 더 이상 백업, 스냅샷 또는 클론 복제하지 않을 애플리케이션 관리를 중지합니다.

앱 관리를 취소하는 경우:

* 기존 백업 및 스냅샷이 삭제됩니다.
* 애플리케이션과 데이터는 사용 가능한 상태로 유지됩니다.


.단계
. 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 앱을 선택합니다.
. 작업 열의 옵션 메뉴에서 * 관리 취소 * 를 선택합니다.
. 정보를 검토합니다.
. "unmanage"를 입력하여 확인합니다.
. 예, 응용 프로그램 관리 취소 * 를 선택합니다.


.결과
Astra Control은 앱 관리를 중지합니다.



== 클러스터 관리를 중지합니다

Astra Control에서 더 이상 관리하지 않으려는 클러스터 관리를 중지합니다.

ifdef::gcp[]


NOTE: 클러스터를 관리하기 전에 클러스터와 연결된 앱의 관리를 해제해야 합니다.

모범 사례로서, GCP를 통해 클러스터를 삭제하기 전에 Astra Control에서 클러스터를 삭제하는 것이 좋습니다.

endif::gcp[]

클러스터 관리를 취소하는 경우:

* 이 작업을 수행하면 Astra Control에서 클러스터를 관리할 수 없습니다. 클러스터 구성을 변경하지 않고 클러스터를 삭제하지 않습니다.
* Astra Trident가 클러스터에서 제거되지 않습니다. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident를 제거하는 방법을 알아보십시오"^].


.단계
. 클러스터 * 를 선택합니다.
. 더 이상 관리하지 않으려는 클러스터의 확인란을 선택합니다.
. Actions * 열의 Options 메뉴에서 * Unmanage * 를 선택합니다.
. 클러스터 관리를 해제할지 확인한 다음 * 예, 관리 취소 * 를 선택합니다.


.결과
클러스터의 상태가 * Removing * 으로 변경됩니다. 그 이후에는 클러스터가 * Clusters * 페이지에서 제거되고 Astra Control에서 더 이상 관리되지 않습니다.



== 클라우드 공급자에서 클러스터 삭제

NetApp 스토리지 클래스에 상주하는 PV(영구적 볼륨)가 있는 Kubernetes 클러스터를 삭제하려면 먼저 아래 방법 중 하나를 따라 PVC(영구 볼륨 클레임)를 삭제해야 합니다. 클러스터를 삭제하기 전에 PVC 및 PV를 삭제하면 클라우드 공급자로부터 예상치 못한 청구서를 받지 않게 됩니다.

* * 방법 #1 *: 클러스터에서 애플리케이션 워크로드 네임스페이스를 삭제합니다. Trident 네임스페이스를_삭제하지_마십시오.
* * 방법 #2 *: PVC와 POD를 삭제하거나 PVS가 마운트된 구축을 삭제합니다.


Astra Control에서 Kubernetes 클러스터를 관리할 경우, 해당 클러스터의 애플리케이션은 클라우드 공급자를 영구 볼륨의 스토리지 백엔드로 사용합니다. PVS를 먼저 제거하지 않고 클라우드 공급자에서 클러스터를 삭제하는 경우 백엔드 볼륨은 클러스터와 함께 _NOT_DELETED가 됩니다.

위의 방법 중 하나를 사용하면 클러스터에서 해당 PVS가 삭제됩니다. 삭제하기 전에 클러스터의 NetApp 스토리지 클래스에 PVS가 없는지 확인하십시오.

클러스터를 삭제하기 전에 영구 볼륨을 삭제하지 않은 경우 클라우드 공급자로부터 백엔드 볼륨을 수동으로 삭제해야 합니다.
