---
sidebar: sidebar 
permalink: get-started/add-private-provider-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 환경을 설정한 후에는 Kubernetes 클러스터를 생성하고 Astra Control Service에 추가할 준비가 된 것입니다. 
---
= Astra Control Service에 프라이빗 공급자 관리 클러스터를 추가합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Service를 사용하여 개인 GKE(Google Kubernetes Engine) 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 AKS 또는 OpenShift 클러스터를 만들고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 AKS 또는 OpenShift 클러스터를 만들고 액세스하는 방법에 대한 자세한 내용은 다음 문서를 참조하십시오.

* https://docs.microsoft.com/azure/aks/private-clusters["프라이빗 AKS 클러스터를 위한 Azure 설명서"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["전용 OpenShift 클러스터를 위한 Azure 문서"^]


Astra Control Service를 사용하여 AKS(프라이빗 Azure Kubernetes Service) 클러스터뿐 아니라 AKS의 프라이빗 Red Hat OpenShift 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 AKS 또는 OpenShift 클러스터를 만들고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 AKS 또는 OpenShift 클러스터를 만들고 액세스하는 방법에 대한 자세한 내용은 다음 문서를 참조하십시오.

* https://docs.microsoft.com/azure/aks/private-clusters["프라이빗 AKS 클러스터를 위한 Azure 설명서"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["전용 OpenShift 클러스터를 위한 Azure 문서"^]


Astra Control Service를 사용하여 전용 EKS(Amazon Elastic Kubernetes Service) 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 EKS 클러스터를 생성하고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 EKS 클러스터 생성 및 액세스에 대한 자세한 내용은 을 참조하십시오 https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html["아마존 EKS 문서"^].

Astra Control Service에 프라이빗 클러스터를 추가하려면 다음 작업을 수행해야 합니다.

. <<Astra Connector를 설치합니다>>
. <<영구 스토리지를 설정합니다>>
. <<Astra Control Service에 프라이빗 공급자 관리 클러스터를 추가합니다>>




== Astra Connector를 설치합니다

프라이빗 클러스터를 추가하기 전에 Astra Control이 클러스터와 통신할 수 있도록 클러스터에 Astra Connector를 설치해야 합니다. 을 참조하십시오 link:install-astra-connector-previous.html["Kubernetes가 아닌 네이티브 워크플로우로 관리되는 프라이빗 클러스터용 Astra Connector의 이전 버전을 설치합니다"] 를 참조하십시오.



== 영구 스토리지를 설정합니다

클러스터의 영구 스토리지를 구성합니다. 영구 스토리지 구성에 대한 자세한 내용은 시작 설명서를 참조하십시오.

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Azure NetApp Files를 사용하여 Microsoft Azure를 설정합니다"^]
* link:set-up-microsoft-azure-with-amd.html["Azure 관리 디스크를 사용하여 Microsoft Azure를 설정합니다"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["Amazon Web Services를 설정합니다"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Google Cloud를 설정합니다"^]


endif::gcp[]



== Astra Control Service에 프라이빗 공급자 관리 클러스터를 추가합니다

이제 Astra Control Service에 프라이빗 클러스터를 추가할 수 있습니다.

Azure Kubernetes Service 및 Google Kubernetes Engine 클러스터를 관리할 때 Astra Control Provisioner 설치 및 라이프사이클 관리에 대한 두 가지 옵션이 있습니다.

* Astra Control Service를 사용하여 Astra Control Provisioner의 라이프사이클을 자동으로 관리할 수 있습니다. 이렇게 하려면 Astra Trident가 설치되어 있지 않고 Astra Control Service를 사용하여 관리하려는 클러스터에 Astra Control Provisioner가 활성화되어 있지 않아야 합니다. 이 경우 클러스터 관리를 시작할 때 Astra Control Service가 Astra Control Provisioner를 자동으로 활성화하며 Astra Control Provisioner 업그레이드는 자동으로 처리됩니다.
* Astra Control Provisioner의 라이프사이클을 직접 관리할 수 있습니다. 이렇게 하려면 Astra Control Service로 클러스터를 관리하기 전에 클러스터에서 Astra Control Provisioner를 활성화합니다. 이 경우 Astra Control Service는 Astra Control Provisioner가 이미 활성화되었음을 감지하여 Astra Control Provisioner 업그레이드를 다시 설치하거나 관리하지 않습니다. 을 참조하십시오 link:../use/enable-acp.html["Astra Control Provisioner를 활성화합니다"^] 단계를 위해 Astra Control Provisioner를 활성화합니다.


Astra Control Service를 사용하여 Amazon Web Services 클러스터를 관리할 때 Astra Control Provisioner에서만 사용할 수 있는 스토리지 백엔드가 필요한 경우 Astra Control Service를 통해 클러스터를 관리하기 전에 클러스터에서 Astra Control Provisioner를 수동으로 활성화해야 합니다. 을 참조하십시오 link:../use/enable-acp.html["Astra Control Provisioner를 활성화합니다"^] Astra Control Provisioner를 활성화하는 단계에 대해 알아보십시오.

.시작하기 전에
[%collapsible%open]
====
ifdef::aws[]

.Amazon Web Services에서 직접 지원합니다
* 클러스터를 생성한 IAM 사용자의 자격 증명이 포함된 JSON 파일이 있어야 합니다. link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["IAM 사용자를 생성하는 방법을 알아봅니다"].
* Amazon FSx for NetApp ONTAP에는 Astra Control Provisioner가 필요합니다. Amazon FSx for NetApp ONTAP를 EKS 클러스터의 스토리지 백엔드로 사용할 계획인 경우 에서 Astra Control Provisioner 정보를 참조하십시오 link:set-up-amazon-web-services.html#eks-cluster-requirements["EKS 클러스터 요구 사항"].
* (선택 사항) 제공해야 하는 경우 `kubectl` 클러스터 생성자가 아닌 다른 IAM 사용자에 대한 클러스터에 대한 명령 액세스는 의 지침을 참조하십시오 https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["Amazon EKS에서 클러스터를 생성한 후 다른 IAM 사용자 및 역할에 대한 액세스를 제공하려면 어떻게 해야 합니까?"^].
* NetApp Cloud Volumes ONTAP를 스토리지 백엔드로 사용하려는 경우 Amazon Web Services와 연동되도록 Cloud Volumes ONTAP를 구성해야 합니다. Cloud Volumes ONTAP를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["설치 설명서"^].


endif::aws[]

ifdef::azure[]

.Microsoft Azure를 참조하십시오
* 서비스 보안 주체를 생성할 때 Azure CLI의 출력이 포함된 JSON 파일이 있어야 합니다. link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["서비스 보안 주체를 설정하는 방법에 대해 알아봅니다"].
+
JSON 파일에 추가하지 않은 경우 Azure 구독 ID도 필요합니다.



* NetApp Cloud Volumes ONTAP를 스토리지 백엔드로 사용하려는 경우 Microsoft Azure와 연동하도록 Cloud Volumes ONTAP를 구성해야 합니다. Cloud Volumes ONTAP를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["설치 설명서"^].


endif::azure[]

ifdef::gcp[]

.Google 클라우드
* 필요한 권한이 있는 서비스 계정에 대한 서비스 계정 키 파일이 있어야 합니다. link:../get-started/set-up-google-cloud.html#create-a-service-account["서비스 계정 설정 방법에 대해 알아보십시오"].
* 클러스터가 프라이빗 인 경우, 를 참조하십시오 https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["인증된 네트워크"^] Astra Control Service IP 주소를 허용해야 합니다.
+
52.188.218.166/32

* NetApp Cloud Volumes ONTAP를 스토리지 백엔드로 사용하려는 경우 Cloud Volumes ONTAP이 Google Cloud와 연동되도록 구성해야 합니다. Cloud Volumes ONTAP를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["설치 설명서"^].


endif::gcp[]

====
.단계
. (선택 사항) Amazon EKS 클러스터를 추가하거나 Astra Control Provisioner의 설치 및 업그레이드를 직접 관리하려는 경우 클러스터에서 Astra Control Provisioner를 활성화합니다. 을 참조하십시오 link:../use/enable-acp.html["Astra Control Provisioner를 활성화합니다"^] 참조하십시오.
. 브라우저에서 Astra Control Service 웹 UI를 엽니다.
. 대시보드에서 * Kubernetes 클러스터 관리 * 를 선택합니다.
+
표시되는 메시지에 따라 클러스터를 추가합니다.

. * 공급자 *: 클라우드 공급자를 선택한 다음 새 클라우드 인스턴스를 생성하는 데 필요한 자격 증명을 제공하거나 사용할 기존 클라우드 인스턴스를 선택하십시오.


ifdef::aws[]

. * Amazon Web Services *: JSON 파일을 업로드하거나 클립보드에서 해당 JSON 파일의 콘텐츠를 붙여넣어 Amazon Web Services IAM 사용자 계정에 대한 세부 정보를 제공합니다.
+
JSON 파일에는 클러스터를 생성한 IAM 사용자의 자격 증명이 포함되어야 합니다.



endif::aws[]

ifdef::azure[]

. * Microsoft Azure *: JSON 파일을 업로드하거나 클립보드에서 해당 JSON 파일의 내용을 붙여넣어 Azure 서비스 보안 주체에 대한 세부 정보를 제공합니다.
+
JSON 파일에는 서비스 보안 주체를 생성할 때 Azure CLI의 출력이 포함되어야 합니다. 또한 구독 ID를 포함할 수 있으므로 Astra에 자동으로 추가됩니다. 그렇지 않으면 JSON을 제공한 후 ID를 수동으로 입력해야 합니다.



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform *: 파일을 업로드하거나 클립보드의 콘텐츠를 붙여 넣어 서비스 계정 키 파일을 제공합니다.
+
Astra Control Service는 서비스 계정을 사용하여 Google Kubernetes Engine에서 실행 중인 클러스터를 검색합니다.



endif::gcp[]

. * 기타 *: 이 탭은 자체 관리형 클러스터에만 사용됩니다.
+
.. * 클라우드 인스턴스 이름 *: 이 클러스터를 추가할 때 생성될 새 클라우드 인스턴스의 이름을 입력합니다. 에 대해 자세히 알아보십시오 link:../use/manage-cloud-instances.html["클라우드 인스턴스"].
.. 다음 * 을 선택합니다.
+
Astra Control Service에는 선택할 수 있는 클러스터 목록이 표시됩니다.

.. * 클러스터 *: 목록에서 Astra Control Service에 추가할 클러스터를 선택합니다.
+

NOTE: 클러스터 목록에서 선택할 때는 * 자격 조건 * 열에 주의해야 합니다. 클러스터가 "부적격" 또는 "부분적으로 적격"인 경우 상태 위로 마우스를 가져가면 클러스터에 문제가 있는지 확인할 수 있습니다. 예를 들어 클러스터에 작업자 노드가 없는 것을 식별할 수 있습니다.





. 다음 * 을 선택합니다.
. (선택 사항) * 스토리지 *: 선택적으로 이 클러스터에 Kubernetes 애플리케이션을 배포할 스토리지 클래스를 선택하여 기본적으로 사용하도록 합니다.
+
.. 클러스터에 대한 새 기본 스토리지 클래스를 선택하려면 * 새 기본 스토리지 클래스 할당 * 확인란을 설정합니다.
.. 목록에서 새 기본 스토리지 클래스를 선택합니다.
+
[NOTE]
====
각 클라우드 공급자의 스토리지 서비스에는 다음과 같은 가격, 성능 및 복원력 정보가 표시됩니다.

ifdef::gcp[]

*** Google Cloud용 Cloud Volumes Service: 가격, 성능 및 복원력 정보
*** Google 영구 디스크: 가격, 성능 또는 복원력 정보를 사용할 수 없습니다


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files: 성능 및 복원력 정보
*** Azure 관리 디스크: 사용 가능한 가격, 성능 또는 복원력 정보가 없습니다


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store: 가격, 성능 또는 복원력 정보를 사용할 수 없습니다
*** NetApp ONTAP용 Amazon FSx: 가격, 성능 또는 복원력 정보 없음


endif::aws[]

*** NetApp Cloud Volumes ONTAP: 가격, 성능 또는 복원력 정보를 제공할 수 없습니다


====
+
각 스토리지 클래스는 다음 서비스 중 하나를 활용할 수 있습니다.





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud용 Cloud Volumes Service"^]
* https://cloud.google.com/persistent-disk/["Google 영구 디스크"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure로 관리되는 디스크"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store를 클릭합니다"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP를 참조하십시오"^]
+
에 대해 자세히 알아보십시오 link:../learn/aws-storage.html["Amazon Web Services 클러스터용 스토리지 클래스입니다"]. 에 대해 자세히 알아보십시오 link:../learn/azure-storage.html["AKS 클러스터용 스토리지 클래스입니다"]. 에 대해 자세히 알아보십시오 link:../learn/choose-class-and-size.html["GKE 클러스터용 저장소 클래스"].

+
.. 다음 * 을 선택합니다.
.. * 검토 및 승인 *: 구성 세부 정보를 검토합니다.
.. 클러스터를 Astra Control Service에 추가하려면 * 추가 * 를 선택합니다.




.결과
이 클라우드 공급자를 위해 추가한 첫 번째 클러스터인 경우 Astra Control Service는 해당 클러스터에서 실행되는 애플리케이션 백업을 위해 클라우드 공급자용 오브젝트 저장소를 생성합니다. (이 클라우드 공급자에 후속 클러스터를 추가할 경우 더 이상 오브젝트 저장소가 생성되지 않습니다.) 기본 스토리지 클래스를 지정한 경우 Astra Control Service는 사용자가 지정한 기본 스토리지 클래스를 설정합니다. Amazon Web Services 또는 Google Cloud Platform에서 관리되는 클러스터의 경우 Astra Control Service는 클러스터에 관리자 계정도 생성합니다. 이 작업은 몇 분 정도 걸릴 수 있습니다.



== 기본 스토리지 클래스를 변경합니다

클러스터의 기본 스토리지 클래스를 변경할 수 있습니다.



=== Astra Control을 사용하여 기본 스토리지 클래스를 변경합니다

Astra Control 내에서 클러스터의 기본 스토리지 클래스를 변경할 수 있습니다. 클러스터에서 이전에 설치된 스토리지 백엔드 서비스를 사용하는 경우 이 방법을 사용하여 기본 스토리지 클래스를 변경하지 못할 수 있습니다(* 기본값으로 설정* 작업은 선택할 수 없음). 이 경우 를 사용할 수 있습니다 <<명령줄을 사용하여 기본 스토리지 클래스를 변경합니다>>.

.단계
. Astra Control Service UI에서 * Clusters * 를 선택합니다.
. 클러스터 * 페이지에서 변경할 클러스터를 선택합니다.
. Storage * 탭을 선택합니다.
. 스토리지 클래스 * 범주를 선택합니다.
. 기본값으로 설정할 스토리지 클래스에 대해 * Actions * 메뉴를 선택합니다.
. Set as default * 를 선택합니다.




=== 명령줄을 사용하여 기본 스토리지 클래스를 변경합니다

Kubernetes 명령을 사용하여 클러스터의 기본 스토리지 클래스를 변경할 수 있습니다. 이 방법은 클러스터의 구성에 관계없이 작동합니다.

.단계
. Kubernetes 클러스터에 로그인합니다.
. 클러스터의 스토리지 클래스를 나열합니다.
+
[source, console]
----
kubectl get storageclass
----
. 기본 스토리지 클래스에서 기본 지정을 제거합니다. <SC_NAME>를 스토리지 클래스 이름으로 바꿉니다.
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. 다른 스토리지 클래스를 기본값으로 표시합니다. <SC_NAME>를 스토리지 클래스 이름으로 바꿉니다.
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. 새 기본 스토리지 클래스를 확인합니다.
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
