---
sidebar: sidebar 
permalink: get-started/check-astra-trident-version.html 
keywords: astra trident, check, version, astra control provisioner 
summary: 자가 관리 클러스터의 경우 올바른 Astra Trident 버전을 사용하고 있는지 확인해야 할 수 있습니다. 
---
= Astra Trident 버전을 확인합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
스토리지 서비스에 Astra Control Provisioner 또는 Astra Trident를 사용하는 자체 관리형 클러스터를 추가하려면 Astra Trident의 설치된 버전이 23.10 이상이어야 합니다.

.단계
. 실행 중인 Astra Trident 버전을 확인합니다.
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
Astra Trident가 설치된 경우 다음과 유사한 출력이 표시됩니다.

+
[listing]
----
NAME      VERSION
trident   24.02.0
----
+
Astra Trident가 설치되지 않은 경우 다음과 유사한 출력이 표시됩니다.

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
. 다음 중 하나를 수행합니다.
+
** Astra Trident 23.01 이하를 실행 중인 경우 다음을 사용합니다 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html["지침"^] Astra Control Provisioner로 업그레이드하기 전에 Astra Trident의 최신 버전으로 업그레이드하십시오. 가능합니다 link:../use/enable-acp.html["직접 업그레이드를 수행합니다"] Astra Trident가 버전 24.02의 4개 릴리즈 윈도우 내에 있는 경우 Astra Control Provisioner 24.02에 등록됩니다. 예를 들어, Astra Trident 23.04에서 Astra Control Provisioner 24.02로 직접 업그레이드할 수 있습니다.
** Astra Trident 23.10 이상을 실행 중인 경우 Astra Control Provisioner가 설치되었는지 확인합니다 link:../use/faq.html#running-acp-check["활성화됨"]. Astra Control Provisioner는 23.10 이전 Astra Control Center 릴리즈에서 작동하지 않습니다. link:../get-started/enable-acp.html["Astra Control Provisioner를 업그레이드합니다"] 최신 기능에 액세스하기 위해 업그레이드하는 Astra Control Center와 동일한 버전을 사용합니다.


. Pod가 실행 중인지 확인합니다.
+
[source, console]
----
kubectl get pods -n trident
----
. 스토리지 클래스가 지원되는 Astra Trident 드라이버를 사용하고 있는지 확인합니다. 공급자 이름은 이어야 합니다 `csi.trident.netapp.io`. 다음 예를 참조하십시오.
+
[source, console]
----
kubectl get sc
----
+
샘플 반응:

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----

