---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 환경을 설정한 후에는 Kubernetes 클러스터를 생성하고 Astra Control Service에 추가할 준비가 된 것입니다. 
---
= Astra Control Service에서 프라이빗 클러스터를 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Service를 사용하여 AKS의 프라이빗 Azure Kubernetes Service(AKS) 및 Red Hat OpenShift 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 AKS 또는 OpenShift 클러스터를 만들고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 AKS 또는 OpenShift 클러스터를 만들고 액세스하는 방법에 대한 자세한 내용은 다음 문서를 참조하십시오.

* https://docs.microsoft.com/azure/aks/private-clusters["프라이빗 AKS 클러스터를 위한 Azure 설명서"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["전용 OpenShift 클러스터를 위한 Azure 문서"^]


Astra Control Service를 사용하여 AKS(프라이빗 Azure Kubernetes Service) 클러스터뿐 아니라 AKS의 프라이빗 Red Hat OpenShift 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 AKS 또는 OpenShift 클러스터를 만들고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 AKS 또는 OpenShift 클러스터를 만들고 액세스하는 방법에 대한 자세한 내용은 다음 문서를 참조하십시오.

* https://docs.microsoft.com/azure/aks/private-clusters["프라이빗 AKS 클러스터를 위한 Azure 설명서"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["전용 OpenShift 클러스터를 위한 Azure 문서"^]


Astra Control Service를 사용하여 전용 EKS(Amazon Elastic Kubernetes Service) 클러스터를 관리할 수 있습니다. 이 지침에서는 이미 전용 EKS 클러스터를 생성하고 원격으로 액세스할 수 있는 안전한 방법을 준비했다고 가정합니다. 전용 EKS 클러스터 생성 및 액세스에 대한 자세한 내용은 을 참조하십시오 https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html["아마존 EKS 문서"^].



== Astra Connector 운용자를 설치한다

프라이빗 클러스터에 Astra Connector 운영자를 설치해야 합니다. 방호 호스트를 사용하는 경우 방호 호스트의 명령줄에서 이러한 명령을 실행하십시오.

.단계
. Astra Connector operator GitHub 리포지토리 클론 생성:
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. 목록을 압축을 푼 운영자 패키지의 최상위 수준으로 변경하여 "ls" 명령으로 "astraconnector_operator.yaML" 파일을 볼 수 있습니다.
. Astra Connector 연산자에 대한 네임스페이스를 만듭니다.
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. astraconnector_operator.yaML 파일을 운용자 namespace에 적용한다.
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 프라이빗 클러스터 구성 요소의 네임스페이스를 생성합니다.
+
[source, console]
----
kubectl create ns astra-connector
----
. 의 지침에 따라 Astra Control API 토큰을 생성합니다 https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Astra 자동화 문서"^].
. Astra Connector 운영자 리포지토리의 config/samples 디렉토리에서 예제 구성 파일을 수정하여 다음 키에 대해 사용자 환경에 특정한 값을 포함시킵니다.
+
** `spec.natssync-client.cloud-bridge-url`
** `spec.astra.token`
** `spec.astra.clusterName`
** `spec.astra.accountId`
+
예를 들면 다음과 같습니다.

+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----


. Astra Connector CRD(Custom Resource Definition)를 적용합니다.
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. Astra Connector의 상태를 확인한다.
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
다음과 유사한 출력이 표시됩니다.

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== 영구 스토리지를 설정합니다

클러스터의 영구 스토리지를 구성합니다. 영구 스토리지 구성에 대한 자세한 내용은 시작 설명서를 참조하십시오.



== 프라이빗 클러스터를 Astra Control Service에 추가합니다

이제 Astra Control Service에 프라이빗 클러스터를 추가할 수 있습니다. 표준 워크플로우를 따라 클러스터를 Astra Control Service에 추가합니다. https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["Astra Control Service에서 Kubernetes 클러스터 관리를 시작합니다"].
