---
sidebar: sidebar 
permalink: get-started/set-up-microsoft-azure-with-amd.html 
keywords: azure, azure netapp files, register, create account, create netapp account, azure subscription, azure permissions, service principal, create service principal, set up azure permissions, set up service principal, setup service principal, setup azure permissions, permissions, create capacity pool, setup capacity pool, set up capacity pool, kubernetes cluster, cluster requirements, version requirements, supported versions, supported regions, azure regions, kubernetes version, linux, image type, networking 
summary: Astra Control Service로 Azure Kubernetes Service 클러스터를 관리하려면 Microsoft Azure 구독을 준비하기 위해 몇 가지 단계가 필요합니다. 
---
= Azure 관리 디스크를 사용하여 Microsoft Azure를 설정합니다
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/


Astra Control Service로 Azure Kubernetes Service 클러스터를 관리하려면 Microsoft Azure 구독을 준비하기 위해 몇 가지 단계가 필요합니다. Azure 관리 디스크를 스토리지 백엔드로 사용하려는 경우 다음 지침을 따르십시오.



== Azure 설정을 위한 빠른 시작

다음 단계를 따라 빠르게 시작하거나 나머지 섹션으로 스크롤하여 자세한 내용을 확인하십시오.



==== Azure Kubernetes Service에 대한 Astra Control Service 요구 사항을 검토합니다

[role="quick-margin-para"]
클러스터가 정상 상태이며 Kubernetes 버전 1.19 이상을 실행 중인지, 노드 풀이 온라인 상태이고 * Linux * 를 실행 중인지 확인합니다. <<Azure Kubernetes Service cluster requirements,이 단계에 대해 자세히 알아보십시오>>.



==== Microsoft Azure에 등록하십시오

[role="quick-margin-para"]
Microsoft Azure 계정을 만듭니다. <<Sign up for Microsoft Azure,이 단계에 대해 자세히 알아보십시오>>.



==== Azure 서비스 보안 주체 만들기

[role="quick-margin-para"]
Contributor 역할이 있는 Azure 서비스 보안 주체를 만듭니다. <<Create an Azure service principal,이 단계에 대해 자세히 알아보십시오>>.



==== 컨테이너 스토리지 인터페이스(CSI) 드라이버 세부 정보를 구성합니다

[role="quick-margin-para"]
CSI 드라이버와 함께 작동하도록 Azure 가입 및 클러스터를 구성해야 합니다. <<Configure Container Storage Interface (CSI) driver details,이 단계에 대해 자세히 알아보십시오>>.



== Azure Kubernetes Service 클러스터 요구사항

Kubernetes 클러스터는 Astra Control Service에서 검색 및 관리할 수 있도록 다음 요구사항을 충족해야 합니다.

Kubernetes 버전:: 클러스터는 Kubernetes 버전 1.19 이상을 실행해야 합니다.
이미지 유형:: 모든 노드 풀의 이미지 유형은 Linux여야 합니다.
클러스터 상태입니다:: 클러스터가 정상 상태에서 실행되고 있어야 하며 오류가 발생한 상태의 작업자 노드가 없는 온라인 작업자 노드가 하나 이상 있어야 합니다.
Azure 지역:: 모범 사례로서, 스토리지 백엔드로 사용하지 않더라도 Azure NetApp Files를 지원하는 영역을 선택해야 합니다. 따라서 성능 요구 사항이 변경될 경우 향후에 Azure NetApp Files를 스토리지 백엔드로 사용할 수 있습니다. https://azure.microsoft.com/en-us/global-infrastructure/services/?products=netapp["지역별 Azure 제품 보기"^].
사설 네트워킹:: 프라이빗 네트워킹은 클러스터에서 활성화되어서는 안 됩니다.
외부 볼륨 스냅샷 컨트롤러:: 클러스터에는 CSI 볼륨 스냅샷 컨트롤러가 설치되어 있어야 합니다. 이 컨트롤러는 K8s 버전 1.21부터 기본적으로 설치되지만 버전 1.19 및 1.20을 실행하는 클러스터를 확인해야 합니다. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["주문형 볼륨 스냅숏용 외부 스냅샷 컨트롤러에 대해 자세히 알아보십시오"^].
CSI 드라이버:: 클러스터에는 적절한 CSI 드라이버가 설치되어 있어야 합니다.




== Microsoft Azure에 등록하십시오

Microsoft Azure 계정이 없는 경우 먼저 Microsoft Azure에 가입합니다.

.단계
. 로 이동합니다 https://azure.microsoft.com/en-us/free/["Azure 구독 페이지입니다"^] Azure 서비스에 가입하려면
. 계획을 선택하고 지침에 따라 구독을 완료합니다.




== Azure 서비스 보안 주체 만들기

Astra Control Service에는 Contributor 역할이 할당된 Azure 서비스 보안 주체가 필요합니다. Astra Control Service는 이 서비스 보안 주체를 사용하여 Kubernetes 애플리케이션 데이터를 사용자 대신 관리합니다.

서비스 보안 주체는 응용 프로그램, 서비스 및 도구와 함께 사용하기 위해 특별히 만들어진 ID입니다. 서비스 보안 주체에 역할을 할당하면 특정 Azure 리소스에 대한 액세스가 제한됩니다.

Azure CLI를 사용하여 서비스 보안 주체를 만들려면 다음 단계를 수행하십시오. 출력 내용을 JSON 파일에 저장하고 나중에 Astra Control Service에 제공해야 합니다. https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli["CLI 사용에 대한 자세한 내용은 Azure 설명서를 참조하십시오"^].

다음 단계에서는 서비스 보안 주체를 만들 수 있는 권한이 있고 Microsoft Azure SDK(az 명령)가 컴퓨터에 설치되어 있다고 가정합니다.

.요구 사항
* 서비스 보안 주체는 일반 인증을 사용해야 합니다. 인증서가 지원되지 않습니다.
* 서비스 보안 주체는 Azure 구독에 대한 Contributor 또는 Owner 액세스 권한을 부여해야 합니다.
* 범위에 대해 선택하는 구독 또는 리소스 그룹에는 AKS 클러스터와 Azure NetApp Files 계정이 포함되어야 합니다.


.단계
. AKS 클러스터가 있는 가입 및 테넌트 ID(Astra Control Service에서 관리하려는 클러스터)를 식별합니다.
+
[source, azureCLI]
----
az configure --list-defaults
az account list --output table
----
. 전체 구독 또는 리소스 그룹을 사용하는 경우에 따라 다음 중 하나를 실행합니다.
+
** 서비스 보안 주체를 만들고 Contributor 역할을 할당하고 클러스터가 상주하는 전체 구독에 범위를 지정합니다.
+
[source, azurecli]
----
az ad sp create-for-rbac --name service-principal-name --role contributor --scopes /subscriptions/SUBSCRIPTION-ID
----
** 서비스 보안 주체를 만들고 Contributor 역할을 할당하고 클러스터가 있는 리소스 그룹을 지정합니다.
+
[source, azurecli]
----
az ad sp create-for-rbac --name service-principal-name --role contributor --scopes /subscriptions/SUBSCRIPTION-ID/resourceGroups/RESOURCE-GROUP-ID
----


. 생성된 Azure CLI 출력을 JSON 파일로 저장합니다.
+
Astra Control Service가 AKS 클러스터를 검색하고 Kubernetes 데이터 관리 작업을 관리할 수 있도록 이 파일을 제공해야 합니다. link:../use/manage-credentials.html["Astra Control Service에서 자격 증명 관리에 대해 자세히 알아보십시오"].

. 선택 사항: JSON 파일에 가입 ID를 추가하면 파일을 선택할 때 Astra Control Service가 자동으로 ID를 채웁니다.
+
그렇지 않으면 메시지가 표시되면 Astra Control Service에 구독 ID를 입력해야 합니다.

+
* 예 *

+
[source, JSON]
----
{
  "appId": "0db3929a-bfb0-4c93-baee-aaf8",
  "displayName": "sp-example-dev-sandbox",
  "name": "http://sp-example-dev-sandbox",
  "password": "mypassword",
  "tenant": "011cdf6c-7512-4805-aaf8-7721afd8ca37",
  "subscriptionId": "99ce999a-8c99-99d9-a9d9-99cce99f99ad"
}
----
. 선택 사항: 서비스 보안 주체를 테스트합니다. 서비스 보안 주체가 사용하는 범위에 따라 다음 예제 명령 중에서 선택합니다.
+
.구독 범위
[source, azurecli]
----
az login --service-principal --username APP-ID-SERVICEPRINCIPAL --password PASSWORD --tenant TENANT-ID
az group list --subscription SUBSCRIPTION-ID
az aks list --subscription SUBSCRIPTION-ID
az storage container list --subscription SUBSCRIPTION-ID
----
+
.리소스 그룹 범위
[source, azurecli]
----
az login --service-principal --username APP-ID-SERVICEPRINCIPAL --password PASSWORD --tenant TENANT-ID
az aks list --subscription SUBSCRIPTION-ID --resource-group RESOURCE-GROUP-ID
----




== 컨테이너 스토리지 인터페이스(CSI) 드라이버 세부 정보를 구성합니다

Azure 관리 디스크를 Astra Control Service와 함께 사용하려면 먼저 1.21 이전의 Kubernetes 버전에 대한 CSI 볼륨 스냅샷 기능을 구성하고 필요한 CSI 드라이버를 설치해야 합니다.



=== Kubernetes 1.19용 CSI 볼륨 스냅샷 컨트롤러를 설치합니다

Kubernetes 버전 1.19를 사용하는 경우 다음 지침에 따라 볼륨 스냅샷 컨트롤러를 설치하십시오.

.단계
. 볼륨 스냅샷 CRD를 설치합니다.
+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
. 스냅샷 컨트롤러를 생성합니다.
+
특정 네임스페이스에 스냅샷 컨트롤러를 적용하려면 적용하기 전에 다음 파일을 다운로드하여 편집합니다.

+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----




=== Kubernetes 1.20용 CSI 볼륨 스냅샷 컨트롤러를 설치합니다

Kubernetes 버전 1.20을 사용하는 경우, 다음 지침에 따라 볼륨 스냅샷 컨트롤러를 설치하십시오.

.단계
. 볼륨 스냅샷 CRD를 설치합니다.
+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
. 스냅샷 컨트롤러를 생성합니다.
+
특정 네임스페이스에 스냅샷 컨트롤러를 적용하려면 적용하기 전에 다음 파일을 다운로드하여 편집합니다.

+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----




=== Azure 구독에서 CSI 드라이버 기능을 활성화합니다

CSI 드라이버를 설치하기 전에 Azure 구독에서 CSI 드라이버 기능을 활성화해야 합니다.

.단계
. Azure 명령줄 인터페이스를 엽니다.
. 다음 명령을 실행하여 드라이버를 등록합니다.
+
[listing]
----
az feature register --namespace "Microsoft.ContainerService" --name "EnableAzureDiskFileCSIDriver"
----
. 다음 명령을 실행하여 변경 내용이 전파되었는지 확인합니다.
+
[listing]
----
'az provider register -n Microsoft.ContainerService
----
+
다음과 유사한 출력이 표시됩니다.



[listing]
----
{
"id": "/subscriptions/b200155f-001a-43be-87be-3edde83acef4/providers/Microsoft.Features/providers/Microsoft.ContainerService/features/EnableAzureDiskFileCSIDriver",
"name": "Microsoft.ContainerService/EnableAzureDiskFileCSIDriver",
"properties": {
   "state": "Registering"
},
"type": "Microsoft.Features/providers/features"
}
----


=== Azure Kubernetes Service 클러스터에 Azure Managed Disk CSI 드라이버를 설치합니다

Azure CSI 드라이버를 설치하여 준비를 완료할 수 있습니다.

.단계
. 로 이동합니다 https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers["Microsoft CSI 드라이버 문서"^].
. 지침에 따라 필요한 CSI 드라이버를 설치합니다.

