---
sidebar: sidebar 
permalink: get-started/set-up-microsoft-azure-with-anf.html 
keywords: azure, azure netapp files, register, create account, create netapp account, azure subscription, azure permissions, service principal, create service principal, set up azure permissions, set up service principal, setup service principal, setup azure permissions, permissions, create capacity pool, setup capacity pool, set up capacity pool, kubernetes cluster, cluster requirements, version requirements, supported versions, supported regions, azure regions, kubernetes version, linux, image type, networking 
summary: Astra Control Service로 Azure Kubernetes Service 클러스터를 관리하려면 Microsoft Azure 구독을 준비하기 위해 몇 가지 단계가 필요합니다. 
---
= Azure NetApp Files를 사용하여 Microsoft Azure를 설정합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Astra Control Service로 Azure Kubernetes Service 클러스터를 관리하려면 Microsoft Azure 구독을 준비하기 위해 몇 가지 단계가 필요합니다. Azure NetApp Files를 스토리지 백엔드로 사용하려는 경우 다음 지침을 따르십시오.



== Azure 설정을 위한 빠른 시작

다음 단계를 따라 빠르게 시작하거나 나머지 섹션으로 스크롤하여 자세한 내용을 확인하십시오.



=== Azure Kubernetes Service에 대한 Astra Control Service 요구 사항을 검토합니다

[role="quick-margin-para"]
클러스터 상태가 양호하고 Kubernetes 버전 1.21.x에서 1.23까지 실행 중이며 노드 풀이 온라인 상태이고 Linux * 등을 실행 중인지 확인합니다. <<Azure Kubernetes Service cluster requirements,이 단계에 대해 자세히 알아보십시오>>.



=== Microsoft Azure에 등록하십시오

[role="quick-margin-para"]
Microsoft Azure 계정을 만듭니다. <<Sign up for Microsoft Azure,이 단계에 대해 자세히 알아보십시오>>.



=== Azure NetApp Files에 등록하십시오

[role="quick-margin-para"]
NetApp 리소스 공급자를 등록합니다. <<Register for Azure NetApp Files,이 단계에 대해 자세히 알아보십시오>>.



=== NetApp 계정을 만듭니다

[role="quick-margin-para"]
Azure 포털에서 Azure NetApp Files로 이동하여 NetApp 계정을 생성합니다. <<Create a NetApp account,이 단계에 대해 자세히 알아보십시오>>.



=== 용량 풀 설정

[role="quick-margin-para"]
영구 볼륨에 대해 하나 이상의 용량 풀을 설정합니다. <<Set up a capacity pool,이 단계에 대해 자세히 알아보십시오>>.



=== Azure NetApp Files에 서브넷 위임

[role="quick-margin-para"]
Astra Control Service가 해당 서브넷에 영구 볼륨을 생성할 수 있도록 Azure NetApp Files에 서브넷을 위임합니다. <<Delegate a subnet to Azure NetApp Files,이 단계에 대해 자세히 알아보십시오>>.



=== Azure 서비스 보안 주체 만들기

[role="quick-margin-para"]
Contributor 역할이 있는 Azure 서비스 보안 주체를 만듭니다. <<Create an Azure service principal,이 단계에 대해 자세히 알아보십시오>>.



=== 선택 사항: Azure 백업 버킷의 중복성을 구성합니다

[role="quick-margin-para"]
기본적으로 Astra Control Service 버킷은 Azure Kubernetes Service 백업을 저장하는 데 사용되며 LRS(Locally Redundant Storage) 이중화 옵션을 사용합니다. 선택적 단계로서 Azure 버킷을 위한 더욱 내구성 있는 이중화 수준을 구성할 수 있습니다. <<Optional: Configure redundancy for Azure backup buckets,이 단계에 대해 자세히 알아보십시오>>.



== Azure Kubernetes Service 클러스터 요구사항

Kubernetes 클러스터는 Astra Control Service에서 검색 및 관리할 수 있도록 다음 요구사항을 충족해야 합니다.

Kubernetes 버전:: 클러스터는 Kubernetes 버전 1.21.x에서 1.23까지 실행 중이어야 합니다.
이미지 유형:: 모든 노드 풀의 이미지 유형은 Linux여야 합니다.
클러스터 상태입니다:: 클러스터가 정상 상태에서 실행되고 있어야 하며 오류가 발생한 상태의 작업자 노드가 없는 온라인 작업자 노드가 하나 이상 있어야 합니다.
Azure 지역:: 클러스터는 Azure NetApp Files를 사용할 수 있는 지역에 상주해야 합니다. https://azure.microsoft.com/en-us/global-infrastructure/services/?products=netapp["지역별 Azure 제품 보기"^].
구독:: 클러스터는 Azure NetApp Files가 설정된 구독에 상주해야 합니다. 구독은 필요할 때 선택할 수 있습니다 <<Register for Azure NetApp Files,Azure NetApp Files에 등록하십시오>>.
VNET:: 다음 VNET 요구 사항을 고려하십시오.
+
--
* 클러스터는 Azure NetApp Files 위임 서브넷에 직접 액세스할 수 있는 VNET에 상주해야 합니다. <<Delegate a subnet to Azure NetApp Files,위임된 서브넷을 설정하는 방법에 대해 알아봅니다>>.
* Kubernetes 클러스터가 다른 VNET에 있는 Azure NetApp Files 위임 서브넷을 통해 피어링된 VNET에 있는 경우 피어링 연결의 양측이 온라인 상태여야 합니다.
* Azure NetApp Files가 있는 VNET(즉시 피어링된 VNets 포함)에서 사용되는 IP 수의 기본 제한은 1,000입니다. https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-resource-limits["Azure NetApp Files 리소스 제한을 봅니다"^].
+
제한에 근접하면 다음 두 가지 옵션을 사용할 수 있습니다.

+
** 가능합니다 https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-resource-limits#request-limit-increase-["한도 증수에 대한 요청을 제출합니다"^]. 도움이 필요하면 NetApp 담당자에게 문의하십시오.
** 새 AKS(Amazon Kubernetes Service) 클러스터를 생성할 때 클러스터에 대한 새 네트워크를 지정합니다. 새 네트워크가 생성되면 새 서브넷을 프로비저닝하고 Azure NetApp Files에 서브넷을 위임합니다.




--


외부 볼륨 스냅샷 컨트롤러:: 클러스터에는 CSI 볼륨 스냅샷 컨트롤러가 설치되어 있어야 합니다. 이 컨트롤러는 K8s 버전 1.21부터 기본적으로 설치되지만 버전 1.19 및 1.20을 실행하는 클러스터를 확인해야 합니다. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["주문형 볼륨 스냅숏용 외부 스냅샷 컨트롤러에 대해 자세히 알아보십시오"^].




=== CSI 볼륨 스냅샷 컨트롤러를 설치합니다

에 설명된 대로 <<Azure Kubernetes Service cluster requirements>>Kubernetes 클러스터에는 CSI 볼륨 스냅샷 컨트롤러가 설치되어 있어야 합니다. 다음 단계에 따라 클러스터에 컨트롤러를 설치합니다.

.K8s 버전 1.19의 단계
. 볼륨 스냅샷 CRD를 설치합니다.
+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
. 스냅샷 컨트롤러를 생성합니다.
+
특정 네임스페이스에 스냅샷 컨트롤러를 적용하려면 적용하기 전에 다음 파일을 다운로드하여 편집합니다.

+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----


.K8s 버전 1.20의 단계
. 볼륨 스냅샷 CRD를 설치합니다.
+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
. 스냅샷 컨트롤러를 생성합니다.
+
특정 네임스페이스에 스냅샷 컨트롤러를 적용하려면 적용하기 전에 다음 파일을 다운로드하여 편집합니다.

+
[source, kubectl]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----




== Microsoft Azure에 등록하십시오

Microsoft Azure 계정이 없는 경우 먼저 Microsoft Azure에 가입합니다.

.단계
. 로 이동합니다 https://azure.microsoft.com/en-us/free/["Azure 구독 페이지입니다"^] Azure 서비스에 가입하려면
. 계획을 선택하고 지침에 따라 구독을 완료합니다.




== Azure NetApp Files에 등록하십시오

NetApp 리소스 공급자를 등록하여 Azure NetApp Files에 액세스하십시오.

.단계
. Azure 포털에 로그인합니다.
. https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-register["Azure NetApp Files 설명서에 따라 NetApp 리소스 공급자를 등록하십시오"^].




== NetApp 계정을 만듭니다

Azure NetApp Files에서 NetApp 계정을 만듭니다.

.단계
. https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-netapp-account["Azure NetApp Files 설명서에 따라 Azure 포털에서 NetApp 계정을 만드십시오"^].




== 용량 풀을 설정합니다

Astra Control Service가 용량 풀에서 영구 볼륨을 프로비저닝할 수 있도록 하나 이상의 용량 풀이 필요합니다. Astra Control Service는 사용자를 위한 용량 풀을 생성하지 않습니다.

Kubernetes 앱의 용량 풀을 설정할 때는 다음 사항을 고려하십시오.

* AKS 클러스터를 Astra Control Service로 관리할 Azure 지역에서 용량 풀을 생성해야 합니다.
* 용량 풀에는 Ultra, Premium 또는 Standard 서비스 수준이 있을 수 있습니다. 각 서비스 수준은 서로 다른 성능 요구 사항을 충족하도록 설계되었습니다. Astra Control Service는 이 세 가지를 모두 지원합니다.
+
Kubernetes 클러스터와 함께 사용할 각 서비스 수준에 대해 용량 풀을 설정해야 합니다.

+
link:../learn/azure-storage.html["Azure NetApp Files의 서비스 수준에 대해 자세히 알아보십시오"].

* Astra Control Service로 보호할 앱의 용량 풀을 생성하기 전에 해당 애플리케이션에 필요한 성능과 용량을 선택하십시오.
+
용량을 적절하게 프로비저닝하면 사용자가 필요에 따라 영구 볼륨을 생성할 수 있습니다. 용량을 사용할 수 없는 경우 영구 볼륨을 프로비저닝할 수 없습니다.

* Azure NetApp Files 용량 풀은 수동 또는 자동 QoS 유형을 사용할 수 있습니다. Astra Control Service는 자동 QoS 용량 풀을 지원합니다. 수동 QoS 용량 풀은 지원되지 않습니다.


.단계
. https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-set-up-capacity-pool["Azure NetApp Files 설명서에 따라 자동 QoS 용량 풀을 설정합니다"^].




== Azure NetApp Files에 서브넷 위임

Astra Control Service가 해당 서브넷에 영구 볼륨을 생성할 수 있도록 Azure NetApp Files에 서브넷을 위임해야 합니다. Azure NetApp Files를 사용하면 VNET에 하나의 위임된 서브넷만 가질 수 있습니다.

피어링된 VNets를 사용하는 경우 피어링 연결의 양쪽이 모두 온라인 상태여야 합니다. 즉, Kubernetes 클러스터가 있는 VNET와 Azure NetApp Files에서 위임한 서브넷이 있는 VNET입니다.

.단계
. https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["Azure NetApp Files 설명서에 따라 Azure NetApp Files에 서브넷을 위임합니다"^].


위임된 서브넷에서 실행 중인 클러스터를 검색하기 전에 약 10분 정도 기다립니다.



== Azure 서비스 보안 주체 만들기

Astra Control Service에는 Contributor 역할이 할당된 Azure 서비스 보안 주체가 필요합니다. Astra Control Service는 이 서비스 보안 주체를 사용하여 Kubernetes 애플리케이션 데이터를 사용자 대신 관리합니다.

서비스 보안 주체는 응용 프로그램, 서비스 및 도구와 함께 사용하기 위해 특별히 만들어진 ID입니다. 서비스 보안 주체에 역할을 할당하면 특정 Azure 리소스에 대한 액세스가 제한됩니다.

Azure CLI를 사용하여 서비스 보안 주체를 만들려면 다음 단계를 수행하십시오. 출력 내용을 JSON 파일에 저장하고 나중에 Astra Control Service에 제공해야 합니다. https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli["CLI 사용에 대한 자세한 내용은 Azure 설명서를 참조하십시오"^].

다음 단계에서는 서비스 보안 주체를 만들 수 있는 권한이 있고 Microsoft Azure SDK(az 명령)가 컴퓨터에 설치되어 있다고 가정합니다.

.요구 사항
* 서비스 보안 주체는 일반 인증을 사용해야 합니다. 인증서가 지원되지 않습니다.
* 서비스 보안 주체는 Azure 구독에 대한 Contributor 또는 Owner 액세스 권한을 부여해야 합니다.
* 범위에 대해 선택하는 구독 또는 리소스 그룹에는 AKS 클러스터와 Azure NetApp Files 계정이 포함되어야 합니다.


.단계
. AKS 클러스터가 있는 가입 및 테넌트 ID(Astra Control Service에서 관리하려는 클러스터)를 식별합니다.
+
[source, azureCLI]
----
az configure --list-defaults
az account list --output table
----
. 전체 구독 또는 리소스 그룹을 사용하는 경우에 따라 다음 중 하나를 실행합니다.
+
** 서비스 보안 주체를 만들고 Contributor 역할을 할당하고 클러스터가 상주하는 전체 구독에 범위를 지정합니다.
+
[source, azurecli]
----
az ad sp create-for-rbac --name service-principal-name --role contributor --scopes /subscriptions/SUBSCRIPTION-ID
----
** 서비스 보안 주체를 만들고 Contributor 역할을 할당하고 클러스터가 있는 리소스 그룹을 지정합니다.
+
[source, azurecli]
----
az ad sp create-for-rbac --name service-principal-name --role contributor --scopes /subscriptions/SUBSCRIPTION-ID/resourceGroups/RESOURCE-GROUP-ID
----


. 생성된 Azure CLI 출력을 JSON 파일로 저장합니다.
+
Astra Control Service가 AKS 클러스터를 검색하고 Kubernetes 데이터 관리 작업을 관리할 수 있도록 이 파일을 제공해야 합니다. link:../use/manage-credentials.html["Astra Control Service에서 자격 증명 관리에 대해 자세히 알아보십시오"].

. 선택 사항: JSON 파일에 가입 ID를 추가하면 파일을 선택할 때 Astra Control Service가 자동으로 ID를 채웁니다.
+
그렇지 않으면 메시지가 표시되면 Astra Control Service에 구독 ID를 입력해야 합니다.

+
* 예 *

+
[source, JSON]
----
{
  "appId": "0db3929a-bfb0-4c93-baee-aaf8",
  "displayName": "sp-example-dev-sandbox",
  "name": "http://sp-example-dev-sandbox",
  "password": "mypassword",
  "tenant": "011cdf6c-7512-4805-aaf8-7721afd8ca37",
  "subscriptionId": "99ce999a-8c99-99d9-a9d9-99cce99f99ad"
}
----
. 선택 사항: 서비스 보안 주체를 테스트합니다. 서비스 보안 주체가 사용하는 범위에 따라 다음 예제 명령 중에서 선택합니다.
+
.구독 범위
[source, azurecli]
----
az login --service-principal --username APP-ID-SERVICEPRINCIPAL --password PASSWORD --tenant TENANT-ID
az group list --subscription SUBSCRIPTION-ID
az aks list --subscription SUBSCRIPTION-ID
az storage container list --subscription SUBSCRIPTION-ID
----
+
.리소스 그룹 범위
[source, azurecli]
----
az login --service-principal --username APP-ID-SERVICEPRINCIPAL --password PASSWORD --tenant TENANT-ID
az aks list --subscription SUBSCRIPTION-ID --resource-group RESOURCE-GROUP-ID
----




== 선택 사항: Azure 백업 버킷의 중복성을 구성합니다

Azure 백업 버킷에 대해 보다 내구성이 뛰어난 이중화 수준을 구성할 수 있습니다. 기본적으로 Astra Control Service 버킷은 Azure Kubernetes Service 백업을 저장하는 데 사용되며 LRS(Locally Redundant Storage) 이중화 옵션을 사용합니다. Azure 버킷에 보다 내구성이 뛰어난 이중화 옵션을 사용하려면 다음을 수행해야 합니다.

.단계
. 필요한 중복 수준을 사용하는 Azure 저장소 계정을 만듭니다 https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal["참조하십시오"^].
. 를 사용하여 새 저장소 계정에 Azure 컨테이너를 생성합니다 https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-portal["참조하십시오"^].
. 컨테이너를 Astra Control Service에 버킷으로 추가합니다. 을 참조하십시오 link:../use/manage-buckets.html#add-an-additional-bucket["추가 버킷을 추가합니다"].
. (선택 사항) 새로 생성한 버킷을 Azure 백업의 기본 버킷으로 사용하려면 이 버킷을 Azure의 기본 버킷으로 설정합니다. 을 참조하십시오 link:../use/manage-buckets.html#change-the-default-bucket["기본 버킷을 변경합니다"].

