---
sidebar: sidebar 
permalink: get-started/supported-deployments.html 
keywords: gke, aks, google kubernetes engine, azure kubernetes service 
summary: Astra Control Service는 클라우드 공급자 환경의 관리되는 Kubernetes 클러스터에서 실행 중인 앱을 관리할 수 있습니다. 
---
= 지원되는 Kubernetes 구축
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Service는 EKS(Amazon Elastic Kubernetes Service)의 관리되는 Kubernetes 클러스터에서 실행 중인 앱과 사용자가 직접 관리하는 클러스터를 관리할 수 있습니다.

Astra Control Service는 GKE(Google Kubernetes Engine)의 관리되는 Kubernetes 클러스터에서 실행 중인 앱과 사용자가 직접 관리하는 클러스터를 관리할 수 있습니다.

Astra Control Service는 Azure Kubernetes Service(AKS)의 관리형 Kubernetes 클러스터에서 실행 중인 앱과 사용자가 직접 관리하는 클러스터를 관리할 수 있습니다.

ifdef::aws[]

* link:set-up-amazon-web-services.html["Astra Control Service용 Amazon Web Services를 설정하는 방법을 알아보십시오"].


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Google Cloud for Astra Control Service를 설정하는 방법을 알아보십시오"].


endif::gcp[]

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Astra Control Service용 Azure NetApp Files를 사용하여 Microsoft Azure를 설정하는 방법에 대해 알아보십시오"].
* link:set-up-microsoft-azure-with-amd.html["Astra Control Service용 Azure 관리 디스크를 사용하여 Microsoft Azure를 설정하는 방법에 대해 알아보십시오"].


endif::azure[]

* link:add-first-cluster.html#start-managing-kubernetes-clusters["Astra Control Service에 추가하기 전에 자체 관리 클러스터를 준비하는 방법을 알아보십시오"].

