---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 알려진 문제점은 이 제품 릴리스를 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다. 
---
= 알려진 문제
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


알려진 문제점은 이 제품 릴리스를 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다.

현재 릴리즈에는 다음과 같은 알려진 문제가 영향을 줍니다.

.인프라
* <<App clones fail after an application is deployed with a set storage class>>
* <<Applications page loads forever when trying to restore an application belonging to a deleted cluster>>
* <<Unable to define an app on a namespace that has been deleted and recreated>>


.백업, 복원, 클론
* <<Restore of an app results in PV size larger than original PV>>
* <<App clones fail using a specific version of PostgreSQL>>
* <<App backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed>>


ifdef::azure[]

* <<Azure backup buckets use LRS redundancy by default>>


endif::azure[]

.기타 문제
* <<Snapshots eventually begin to fail when using external-snapshotter version 4.2.0>>
* <<App data management operations fail with Internal Service Error (500) when Astra Trident is offline>>




== 애플리케이션 클론을 세트 스토리지 클래스로 구축한 후에는 애플리케이션 클론이 실패합니다

애플리케이션이 명시적으로 설정된 스토리지 클래스(예: 'helm install...-set global.storageClass=NetApp-cvs-perf-extreme')로 구축된 후 애플리케이션을 복제하려는 이후에 타겟 클러스터에 원래 지정된 스토리지 클래스가 있어야 합니다. 명시적으로 설정된 스토리지 클래스를 가진 애플리케이션을 동일한 스토리지 클래스가 없는 클러스터로 클론 복제하면 실패합니다. 이 시나리오에서는 복구 단계가 없습니다.



== 삭제된 클러스터에 속한 애플리케이션을 복구하려고 하면 애플리케이션 페이지가 영구적으로 로드됩니다

응용 프로그램 페이지에서 삭제된 클러스터에서 응용 프로그램을 복원하려고 하면 응용 프로그램 페이지의 로딩이 절대 마무리되지 않습니다. 이 문제를 해결하려면 응용 프로그램 목록 페이지의 앱 작업 메뉴에서 앱을 복원하십시오.



== 삭제되어 다시 생성된 네임스페이스에 앱을 정의할 수 없습니다

네임스페이스로 응용 프로그램을 정의하고 네임스페이스를 삭제한 다음 같은 네임스페이스에 응용 프로그램을 다시 설치하면 409 오류 코드와 함께 작업이 실패합니다. 다시 생성된 네임스페이스를 사용하여 앱을 정의하려면 먼저 이전 응용 프로그램 인스턴스를 삭제합니다.



== 앱 복원으로 인해 PV 크기가 원래 PV보다 큽니다

백업을 생성한 후 영구 볼륨의 크기를 조정한 다음 해당 백업에서 복원하는 경우 영구 볼륨 크기는 백업 크기를 사용하는 대신 PV의 새 크기와 일치합니다.



== 특정 버전의 PostgreSQL을 사용하여 앱 클론이 실패합니다

동일한 클러스터 내의 앱 클론은 Bitnami PostgreSQL 11.5.0 차트와 함께 일관되게 실패합니다. 클론을 성공적으로 생성하려면 이전 또는 이후 버전의 차트를 사용하십시오.



== 클러스터를 관리하고 볼륨을 추가한 경우 앱 백업 및 스냅숏이 실패합니다

이 시나리오에서 백업 및 스냅샷이 실패하고 UI 500 오류가 표시됩니다. 이 문제를 해결하려면 앱 목록을 새로 고치십시오.

ifdef::azure[]



== Azure 백업 버킷은 기본적으로 LRS 이중화를 사용합니다

기본적으로 Astra Control Service 버킷은 Azure Kubernetes Service 백업을 저장하는 데 사용되며 LRS(Locally Redundant Storage) 이중화 옵션을 사용합니다. Azure 버킷에 보다 내구성이 뛰어난 이중화 옵션을 사용하려면 Azure 클라우드 공급자 설정 지침의 옵션 단계를 참조하십시오.

* link:../get-started/set-up-microsoft-azure-with-amd.html["Azure 관리 디스크를 사용하여 Microsoft Azure를 설정합니다"]
* link:../get-started/set-up-microsoft-azure-with-anf.html["Azure NetApp Files를 사용하여 Microsoft Azure를 설정합니다"]


endif::azure[]



== 외부 스냅샷 버전 4.2.0 사용 시 결국 스냅숏이 실패하기 시작합니다

Kubernetes 1.20 또는 1.21이 포함된 Kubernetes 스냅샷 컨트롤러(외부 스냅샷 샷터라고도 함) 버전 4.2.0 을 사용하면 스냅샷이 실패할 수 있습니다. 이를 방지하려면 다른 을 사용하십시오 https://kubernetes-csi.github.io/docs/snapshot-controller.html["지원되는 버전입니다"^] 4.2.1과 같은 외부 스냅샷 기능을 Kubernetes 버전 1.20 또는 1.21과 함께 사용할 수 있습니다.



== Astra Trident가 오프라인일 때 내부 서비스 오류(500)와 함께 앱 데이터 관리 작업이 실패했습니다

앱 클러스터의 Astra Trident가 오프라인 상태가 되고 다시 온라인 상태가 되고 앱 데이터 관리를 시도할 때 500 내부 서비스 오류가 발생하는 경우, 앱 클러스터의 모든 Kubernetes 노드를 다시 시작하여 기능을 복원합니다.
