---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations, interoperability 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/


알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== 일반 제한 사항

지원되는 Kubernetes 구현에서 Astra Control Service의 Kubernetes 클러스터 관리에 영향을 미치는 요소는 다음과 같습니다.



=== 비정상적인 Pod는 앱 관리에 영향을 줍니다

관리 애플리케이션에 상태가 불량한 Pod가 있는 경우 Astra Control Service는 새 백업 및 클론을 생성할 수 없습니다.



=== Astra Trident가 클러스터에서 제거되지 않았습니다

Astra Control Service에서 클러스터를 관리 해제하면 Astra Trident가 클러스터에서 자동으로 제거되지 않습니다. Astra Trident를 제거하려면 다음을 수행해야 합니다 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident 문서의 다음 단계를 따릅니다"^].



=== Postgres POD에 대한 기존 연결로 인해 오류가 발생합니다

Postgres Pod에서 작업을 수행할 때 psql 명령을 사용하기 위해 POD 내에서 직접 연결하면 안 됩니다. Astra Control Service는 데이터베이스를 고정 및 고정 해제할 수 있도록 psql 액세스 권한이 필요합니다. 기존 접속이 있는 경우 스냅샷, 백업 또는 클론이 실패합니다.



== GKE 클러스터 관리에 대한 제한 사항

GKE(Google Kubernetes Engine)에서 Kubernetes 클러스터 관리에 다음과 같은 제한 사항이 적용됩니다.



=== 하나의 GCP 프로젝트와 하나의 서비스 계정이 지원됩니다

Astra Control Service는 하나의 Google Cloud Platform 프로젝트와 하나의 서비스 계정을 지원합니다. Astra Control Service에 서비스 계정을 두 개 이상 추가할 수 없으며 서비스 계정 자격 증명을 회전해서는 안 됩니다.



=== Google Marketplace 앱의 유효성을 검증하지 않았습니다

NetApp은 Google Marketplace에서 배포된 앱을 검증하지 않았습니다. 일부 사용자는 Google Marketplace에서 배포된 Postgres, MariaDB 및 MySQL 앱의 검색 또는 백업 관련 문제를 보고합니다.

Astra Control Service와 함께 사용하는 애플리케이션 유형에 관계없이 재해 복구 요구 사항을 충족할 수 있도록 항상 백업 및 복원 워크플로우를 직접 테스트해야 합니다.



=== 영구 볼륨 제한

Google Cloud 지역당 최대 100개의 볼륨을 가질 수 있습니다. 이 제한에 도달하면 새 클론이나 볼륨을 생성하지 못합니다. link:../support/get-help.html["볼륨 제한을 늘리려면 지원 부서에 문의하십시오"].



== 앱 관리 제한 사항

다음 제한 사항은 Astra Control Service의 애플리케이션 관리에 영향을 줍니다.



=== PASS by reference operator를 사용하여 설치된 앱의 클론이 실패할 수 있습니다

Astra Control은 네임스페이스 범위 연산자와 함께 설치된 앱을 지원합니다. 이러한 연산자는 일반적으로 "pass-by-reference" 아키텍처가 아니라 "pass-by-value"로 설계되었습니다. 다음은 이러한 패턴을 따르는 일부 운영자 앱에 대한 설명입니다.

* https://github.com/k8ssandra/cass-operator/tree/v1.7.1["아파치 K8ssandra"^]
* https://github.com/jenkinsci/kubernetes-operator["젠킨스 CI"^]
* https://github.com/percona/percona-xtradb-cluster-operator["Percona XtraDB 클러스터"^]


Astra Control은 "pass-by-reference" 아키텍처(예: CockroachDB 운영자)로 설계된 운영자를 복제하지 못할 수 있습니다. 이러한 유형의 클론 복제 작업 중에 클론 복제 운영자는 클론 복제 프로세스의 일부로 고유한 새로운 암호가 있음에도 불구하고 소스 운영자의 Kubernetes 암호를 참조하려고 합니다. Astra Control이 소스 운영자의 Kubernetes 암호를 모르기 때문에 클론 작업이 실패할 수 있습니다.
